// Generated from Support/inspo.json by scripts/make-inspo.sh. Don't edit.

extension Inspo {
    static let videos: [Video] = [
        .init(number: 1, youtube: "KxGRhd_iWuE", daily: true,
              title: "never give up", japanese: "あきらめかけているあなた"),
        .init(number: 2, youtube: "AO8RNNxEAjM", daily: true,
              title: "when you can't get motivated", japanese: "やる気が起きないあなたに"),
        .init(number: 3, youtube: "cqroRiHMGLs", daily: true,
              title: "when you keep saying you can't", japanese: "無理とか出来ないとか言っちゃうあなたに"),
        .init(number: 4, youtube: "9LRmzqZ6sXI", daily: true,
              title: "when looks fool you", japanese: "見かけに騙されちゃうあなたに"),
        .init(number: 5, youtube: "I9UFRHgdOBQ", daily: false,
              title: "when you want to win at look-that-way", japanese: "そっち向いてホイッ！で勝ちたいあなたに"),
        .init(number: 6, youtube: "Frar_GMjR6M", daily: true,
              title: "when you can't believe in yourself", japanese: "自信が持てないあなたに"),
        .init(number: 7, youtube: "Bt1Q47D6Xh8", daily: true,
              title: "when you can't give it everything", japanese: "出しきれないあなたに"),
        .init(number: 8, youtube: "Hw2q1lKio8g", daily: true,
              title: "when you can't feel anything", japanese: "何かを感じれないあなたに"),
        .init(number: 9, youtube: "FbhSpnA3FEU", daily: false,
              title: "when your meals don't satisfy you", japanese: "食事に満足できないあなたに"),
        .init(number: 10, youtube: "M0eL-jttkEw", daily: true,
              title: "when you're stuck in fixed ideas", japanese: "固定観念を持っているあなたに"),
        .init(number: 11, youtube: "xXfJ5OcaiIQ", daily: true,
              title: "when you can't let things go", japanese: "サバサバできないあなたに"),
        .init(number: 12, youtube: "Rtugrnveonw", daily: false,
              title: "when you want to feel french", japanese: "フランス語を感じたいあなたに"),
        .init(number: 13, youtube: "Pgnnsjh5a4M", daily: false,
              title: "when you can't make small talk", japanese: "トークができないあなたに"),
        .init(number: 14, youtube: "7RH1QD6RUJM", daily: false,
              title: "when you want to feel france", japanese: "フランスを感じたいあなたに"),
        .init(number: 15, youtube: "am2mNGirfEE", daily: false,
              title: "when you want to feel nature", japanese: "ネイチャーに感じたいあなたにPart5"),
        .init(number: 16, youtube: "fax4dK7sRbU", daily: false,
              title: "when you want to feel nature", japanese: "ネイチャーを感じたいあなたにPart１"),
        .init(number: 17, youtube: "cRcCktNTak0", daily: true,
              title: "when you keep looking back", japanese: "過去ばかり振り返ってしまうあなたに"),
        .init(number: 18, youtube: "aPoi08LD2-c", daily: false,
              title: "when you want to feel nature", japanese: "ネイチャーを感じたいあなたにPart2"),
        .init(number: 19, youtube: "1AkuN0IGsiU", daily: false,
              title: "when you want to feel nature", japanese: "ネイチャーを感じたいあなたにPart3"),
        .init(number: 20, youtube: "-l70T7qvZ6g", daily: true,
              title: "when you can't take a step forward", japanese: "一歩前に進めないあなたに"),
        .init(number: 21, youtube: "LABoKsMTOIc", daily: false,
              title: "when you want to feel nature", japanese: "ネイチャーを感じたいあなたにPart4"),
        .init(number: 22, youtube: "1D_pDimyIhw", daily: true,
              title: "when you can't take a fall well", japanese: "上手に受け身ができないあなたに"),
        .init(number: 23, youtube: "q7L_ZpAm8sI", daily: true,
              title: "when you want to get serious", japanese: "本気になりたいあなたに"),
        .init(number: 24, youtube: "AXnJODC3XrQ", daily: true,
              title: "when you can't be yourself", japanese: "自分らしさを出せないあなたに"),
        .init(number: 25, youtube: "13e7xiMrRJg", daily: true,
              title: "when traffic gets to you", japanese: "渋滞にイライラするあなたに"),
        .init(number: 26, youtube: "aoAiSd-8-mI", daily: true,
              title: "when the rain gets you down", japanese: "雨で憂鬱なあなたに"),
        .init(number: 27, youtube: "ZvhXyrBuJ-E", daily: false,
              title: "when you want your suit fresh every day", japanese: "スーツを毎日フレッシュに着たいあなたに"),
        .init(number: 28, youtube: "NjcG5RiMJNc", daily: true,
              title: "when you can't say thank you", japanese: "ありがとうが言えないあなたに"),
        .init(number: 29, youtube: "jl4ZwOfuIXQ", daily: true,
              title: "when you're fighting sleep", japanese: "睡魔と格闘しているあなたにPart3"),
        .init(number: 30, youtube: "VFJcn2x1OGw", daily: true,
              title: "when you're fighting sleep", japanese: "睡魔と格闘しているあなたにPart4"),
        .init(number: 31, youtube: "Qy-fn7cXim0", daily: true,
              title: "when you're fighting sleep", japanese: "睡魔と格闘しているあなたにPart5"),
        .init(number: 32, youtube: "yS6QvC1S9Cc", daily: true,
              title: "when you can't say your thanks out loud", japanese: "感謝の気持ちを口に出せないあなたに"),
        .init(number: 33, youtube: "tmqagdoQfM4", daily: true,
              title: "when you're fighting sleep", japanese: "睡魔と格闘しているあなたにPart2"),
        .init(number: 34, youtube: "rStCUXOB0TI", daily: true,
              title: "when you're fighting sleep", japanese: "睡魔と格闘しているあなたにPart1"),
        .init(number: 35, youtube: "zbaFP2CQk-Q", daily: true,
              title: "when you want to go for gold", japanese: "ゴールドになりたいあなたに…"),
        .init(number: 36, youtube: "nzmzu7ofzCw", daily: true,
              title: "when you're giving it your all", japanese: "一所懸命頑張っているあなたに"),
        .init(number: 37, youtube: "kwl-PZMYx3U", daily: true,
              title: "when you think you can live alone", japanese: "一人で生きられるあなたに…"),
        .init(number: 38, youtube: "K8TYE26eAz8", daily: false,
              title: "when you want to be a good listener", japanese: "徹子の部屋なあなたに"),
        .init(number: 39, youtube: "IRVxpdz7xJQ", daily: true,
              title: "when you're shallower than tea", japanese: "お茶のように深みのないあなたに…"),
        .init(number: 40, youtube: "3XJJ44YfRQQ", daily: true,
              title: "when you want to shine", japanese: "輝きたいあなたに"),
        .init(number: 41, youtube: "iZW-biK8YBE", daily: true,
              title: "when you fidget and hold back", japanese: "もじもじしちゃうあなたに…"),
        .init(number: 42, youtube: "ShW4ZbacgIc", daily: true,
              title: "when you only notice the shadows", japanese: "影ばかり気にしてしまうあなたに…"),
        .init(number: 43, youtube: "fcxIonI6Xic", daily: true,
              title: "when you're shy", japanese: "恥ずかしがり屋のあなたに…"),
        .init(number: 44, youtube: "VCOT1BbeoLk", daily: true,
              title: "when you judge people by their looks", japanese: "人を見かけで判断してしまうあなたに…"),
        .init(number: 45, youtube: "KDQ5NI3eXQ0", daily: true,
              title: "when you want to say how you feel", japanese: "想いを伝えたいあなたに…スペイン編"),
        .init(number: 46, youtube: "5TFy5KZairo", daily: true,
              title: "when you can't wait", japanese: "待てないあなたに"),
        .init(number: 47, youtube: "1sYTUWuyl4Y", daily: false,
              title: "when you need cheering up", japanese: "くまもんに元気をもらいたいあなたに…"),
        .init(number: 48, youtube: "t7NYfo67cDc", daily: true,
              title: "when you want to let nature take you", japanese: "自然に身をゆだねたいあなたに"),
        .init(number: 49, youtube: "fdln38t6Nko", daily: false,
              title: "when you want depth", japanese: "お茶のように渋くなりたいあなたに…"),
        .init(number: 50, youtube: "DLaedW-NrOc", daily: true,
              title: "when you want to go with the flow", japanese: "川の流れに身を任せたいあなたに"),
        .init(number: 51, youtube: "y-1OAIA1mwk", daily: true,
              title: "when you've got it wrong", japanese: "勘違いしているあなたに"),
        .init(number: 52, youtube: "uI-gVhENee0", daily: true,
              title: "when you want to start together", japanese: "みんなでスタートしたいあなたに"),
        .init(number: 53, youtube: "SVfuSsXPSbc", daily: true,
              title: "when you don't want to bounce off", japanese: "跳ね返されたくないあなたに"),
        .init(number: 54, youtube: "f5OMGQW4v-E", daily: true,
              title: "when you think half-hearted is bad", japanese: "中途半端がダメだと思っているあなたに…"),
        .init(number: 55, youtube: "IlE5AE6XU6o", daily: true,
              title: "when you can't feel what others feel", japanese: "人の思いを感じられないあなたに"),
        .init(number: 56, youtube: "8BNNbXnnLMM", daily: false,
              title: "when you want to spin round and round", japanese: "ぐるぐる回りたいあなたに"),
        .init(number: 57, youtube: "8wJYOBzZoFs", daily: true,
              title: "when you can't enjoy yourself anywhere", japanese: "どこでも楽しめないあなたに…"),
        .init(number: 58, youtube: "13Hsr2cWU2o", daily: true,
              title: "when you're lost for what to do", japanese: "戸惑ってしまうあなたに…"),
        .init(number: 59, youtube: "PdBlee8ZPX4", daily: true,
              title: "when images sway you", japanese: "イメージに左右されているあなたに…"),
        .init(number: 60, youtube: "Fz3jcYe8oCU", daily: true,
              title: "when your heart is in a black hole", japanese: "心がブラックホールにいるあなたに"),
        .init(number: 61, youtube: "CrvPZD3cT4w", daily: false,
              title: "when you're tired of saying good work", japanese: "お疲れさまですに疑問を感じているあなたに…"),
        .init(number: 62, youtube: "A9K3UciyyPQ", daily: true,
              title: "when you can't live in the now", japanese: "今を生きれないあなたに"),
        .init(number: 63, youtube: "9T8kvWbzp0c", daily: true,
              title: "when you want to get along with everyone", japanese: "みんなと仲良くしたいあなたに"),
        .init(number: 64, youtube: "eufHdd1gGGI", daily: false,
              title: "when you want to draw people in", japanese: "マグネットパワーインされたいあなたに"),
        .init(number: 65, youtube: "--SiDaFM2h0", daily: true,
              title: "when you're not fighting yourself", japanese: "自分と戦えていないあなたに"),
        .init(number: 66, youtube: "QViVWFS10Hc", daily: true,
              title: "when you can't believe in yourself", japanese: "自信が持てないあなたに…感謝祭ver"),
        .init(number: 67, youtube: "ACzESLeff3s", daily: true,
              title: "when you're bad at getting things across", japanese: "伝えることが苦手なあなたに…"),
        .init(number: 68, youtube: "J-Scu0O23R0", daily: true,
              title: "when you want to cheer yourself up", japanese: "自分を元気づけたいあなたに"),
        .init(number: 69, youtube: "a568Txh1CJU", daily: true,
              title: "when you can't make up your mind", japanese: "なかなか決めれないあなたに…"),
        .init(number: 70, youtube: "YjuVqJ1fS-M", daily: true,
              title: "when you're anxious about what's next", japanese: "今後の自分が不安なあなたに…"),
        .init(number: 71, youtube: "UTTDhe_b0sA", daily: true,
              title: "when you want to become a legend", japanese: "伝説になりたいあなたに"),
        .init(number: 72, youtube: "HfiwfNqd5Bo", daily: false,
              title: "when things feel good", japanese: "気持ちいいな～と思っているあなたに"),
        .init(number: 73, youtube: "QNTeB0czkXA", daily: true,
              title: "you're a world heritage site too", japanese: "あなたも世界遺産！"),
        .init(number: 74, youtube: "AoUr_B5fM4c", daily: true,
              title: "when you're hungry for it", japanese: "Hungryに応援したいあなたに"),
        .init(number: 75, youtube: "ipefkerDosY", daily: false,
              title: "when you want to feel tradition", japanese: "伝統を感じたいあなたに…"),
        .init(number: 76, youtube: "EZuQKc8dUg0", daily: true,
              title: "when you want to give others courage", japanese: "勇気を与えられる人になりたいあなたに…"),
        .init(number: 77, youtube: "vhtYLkWGuxM", daily: true,
              title: "when you're about to give up", japanese: "できないと諦めそうなあなたに…"),
        .init(number: 78, youtube: "3V57MIc9hEs", daily: true,
              title: "when you can't give it everything", japanese: "出しきれないあなたに…"),
        .init(number: 79, youtube: "FVn6s6PvDT8", daily: true,
              title: "when you want to keep a calm heart", japanese: "心を冷静に保ちたいあなたに…"),
        .init(number: 80, youtube: "4z8z12rOhq4", daily: true,
              title: "when you want to cry it all out", japanese: "涙を出しきりたいあなたに…"),
        .init(number: 81, youtube: "cI8N0oUhXz8", daily: false,
              title: "when you want to feel sports culture", japanese: "スポーツ文化を感じたいあなたに…"),
        .init(number: 82, youtube: "eg-Nk_lLcEs", daily: false,
              title: "when you like oranges", japanese: "オレンジが好きなあなたに…"),
        .init(number: 83, youtube: "ahDxH2PU8qk", daily: true,
              title: "when you want your dream to come true", japanese: "夢を叶えたいあなたに"),
        .init(number: 84, youtube: "-EBBTBqcA2U", daily: true,
              title: "when you're selfish", japanese: "わがままなあなたに"),
        .init(number: 85, youtube: "xhL4RG-mrV4", daily: true,
              title: "when you don't want to stop", japanese: "止まりたくないあなたに…"),
        .init(number: 86, youtube: "2JuKqgcSHyE", daily: true,
              title: "when you can't lay it all bare", japanese: "全てをさらけ出せないあなたに…"),
        .init(number: 87, youtube: "6eKkzgEywvI", daily: true,
              title: "when you miss what matters right in front of you", japanese: "目の前の大事なものに気づけていないあなたに"),
        .init(number: 88, youtube: "XPrXCVc57vA", daily: true,
              title: "when your heart is scattered", japanese: "心が散っているあなたに"),
        .init(number: 89, youtube: "seExlemsTu0", daily: false,
              title: "when you want to start over", japanese: "ハリー・ポッターでリボーンしたいあなたに"),
        .init(number: 90, youtube: "lzirT7ahGg8", daily: true,
              title: "when your heart is weak", japanese: "心が弱いあなたに"),
        .init(number: 91, youtube: "tnMRoyVdxmA", daily: true,
              title: "when you can't open up", japanese: "心が開けないあなたに"),
        .init(number: 92, youtube: "TdsL7hYmc94", daily: true,
              title: "when you can't move forward", japanese: "前に進めないあなたに"),
        .init(number: 93, youtube: "O1JEm3GTgy0", daily: true,
              title: "when your heart is in full bloom", japanese: "心が満開のあなたに"),
        .init(number: 94, youtube: "FQMX48sgMMQ", daily: true,
              title: "when you want to be number one", japanese: "1位になりたいあなたに"),
        .init(number: 95, youtube: "Kxt_S-JKoew", daily: true,
              title: "when you want to feel better", japanese: "元気になりたいあなたに"),
        .init(number: 96, youtube: "Kozb9ZtUdMs", daily: true,
              title: "when you want real strength", japanese: "本気の強さを持ちたいあなたに"),
        .init(number: 97, youtube: "CPQkgr7JYWg", daily: false,
              title: "when you're not scared of bears", japanese: "熊が怖くないあなたに"),
        .init(number: 98, youtube: "0GFuP7PKsYk", daily: true,
              title: "when you want a gold medal mind", japanese: "金メンタリストになりたいあなたに"),
        .init(number: 99, youtube: "Ylgy4ZTQTwE", daily: true,
              title: "when you want to meet a new you", japanese: "新しい自分に出会いたいあなたへ"),
        .init(number: 100, youtube: "DkmknQEej7w", daily: true,
              title: "when you want results right away", japanese: "すぐに結果を出したがるあなたへ"),
        .init(number: 101, youtube: "5soMHmWxZn4", daily: true,
              title: "when your heart wavers", japanese: "心がぶれちゃうあなたに"),
        .init(number: 102, youtube: "kEGQuvDRZfI", daily: true,
              title: "when you think nothing good happens", japanese: "いいことないと思っているあなたに"),
        .init(number: 103, youtube: "YCNcq6W9cGA", daily: true,
              title: "when you want to shine like a rainbow", japanese: "虹のように輝きたいあなたに"),
        .init(number: 104, youtube: "EHyCgvvJ0HA", daily: true,
              title: "when you want to grow up tough", japanese: "わんぱくでもいい、たくましく育ちたいあなたへ"),
        .init(number: 105, youtube: "D_xot4jhwK8", daily: true,
              title: "when you can't stand tall as yourself", japanese: "自分らしく堂々とできないあなたに"),
        .init(number: 106, youtube: "weU2gHWuXKU", daily: true,
              title: "when you want to smile", japanese: "笑顔になりたいあなたに"),
        .init(number: 107, youtube: "oHcf-E4nL7E", daily: true,
              title: "when you can't smile", japanese: "笑顔ができないあなたに"),
        .init(number: 108, youtube: "lKAEpXcurTo", daily: true,
              title: "when you want to take it on with a smile", japanese: "笑顔で挑みたいあなたに"),
        .init(number: 109, youtube: "mOwil4iifO8", daily: true,
              title: "when you can't get your feelings across", japanese: "自分の思いを伝えられないあなたに"),
        .init(number: 110, youtube: "jeE-_Q5zx60", daily: true,
              title: "when you can't laugh", japanese: "笑えないあなたに"),
        .init(number: 111, youtube: "bW_12K63VRM", daily: true,
              title: "when you're studying for exams", japanese: "受験生のあなたに"),
        .init(number: 112, youtube: "Z3kuHtAfKow", daily: true,
              title: "when you think you can do it all alone", japanese: "自分一人で何でもできると思っているあなたに"),
        .init(number: 113, youtube: "9bHdIgsR-mA", daily: true,
              title: "when you think you don't stand out", japanese: "自分は目立たないと思っているあなたに"),
        .init(number: 114, youtube: "QpAJUR7p_No", daily: true,
              title: "when you take being alive for granted", japanese: "生きていることが当たり前だと思っているあなたに"),
        .init(number: 115, youtube: "ByKU3mF8mLI", daily: false,
              title: "when you want to hear you can do it", japanese: "テゥ・プ・ル・フェルして欲しいあなたに"),
        .init(number: 116, youtube: "5ATdeqbLtDw", daily: true,
              title: "when you want to say how you feel", japanese: "思いを伝えたいあなたに"),
        .init(number: 117, youtube: "5e7unFhiD_M", daily: true,
              title: "when worry stops you trying", japanese: "不安でチャレンジできないあなたに"),
        .init(number: 118, youtube: "4a0RQY5yzgw", daily: true,
              title: "when you really want to smile", japanese: "どーしても笑顔になりたいあなたに"),
        .init(number: 119, youtube: "AIccKhuwKsI", daily: true,
              title: "when you're studying for exams", japanese: "受験生のあなたに03"),
        .init(number: 120, youtube: "ldWdjelof-g", daily: true,
              title: "when your heart is weak", japanese: "心が弱いあなたに"),
        .init(number: 121, youtube: "ioCshGZKf4I", daily: true,
              title: "when you can't lay it all bare", japanese: "すべてをさらけ出せないあなたに"),
        .init(number: 122, youtube: "P2GNhcawrfI", daily: true,
              title: "when you're studying for exams", japanese: "受験生のあなたに01"),
        .init(number: 123, youtube: "25vtPJrLq4I", daily: true,
              title: "when you're studying for exams", japanese: "受験生のあなたに02"),
        .init(number: 124, youtube: "0_wY-DV2ceY", daily: true,
              title: "when you let your guard down", japanese: "脇が甘いあなたに"),
        .init(number: 125, youtube: "vMz-rBzJkww", daily: true,
              title: "when your heart is cold", japanese: "心が寒いあなたに…"),
        .init(number: 126, youtube: "s0cZRIQflNM", daily: true,
              title: "when you think you can't be a champion", japanese: "チャンピオンになれないと思っているあなたに…"),
        .init(number: 127, youtube: "Qj6XQMa4jUE", daily: true,
              title: "when you keep complaining", japanese: "いたいようって言っちゃうあなたに"),
        .init(number: 128, youtube: "4eiKa6GVgYc", daily: true,
              title: "when you think your surroundings aren't good enough", japanese: "良い環境がないと思っているあなたに"),
        .init(number: 129, youtube: "-QmpPswdXWc", daily: true,
              title: "when you're waiting for something good to happen", japanese: "いいことないかなぁと思っているあなたに"),
        .init(number: 130, youtube: "uhgpiWS1130", daily: true,
              title: "when your heart is scattered", japanese: "心が散っちゃったあなたに"),
        .init(number: 131, youtube: "Yag0KMbWNl8", daily: false,
              title: "when you want to watch like the french", japanese: "フランス人のようにおしゃれに観戦したいあなたに"),
        .init(number: 132, youtube: "tyfaN_5a2Z8", daily: true,
              title: "when you want to stand at the center", japanese: "センターに立ちたいと思っているあなたに"),
        .init(number: 133, youtube: "2oPT5vxcaV0", daily: true,
              title: "when you're at the center", japanese: "センターに立ったあなたに"),
        .init(number: 134, youtube: "GTXt3NLnoHg", daily: true,
              title: "when the rain makes you sulk", japanese: "雨（？）ったれているあなたに"),
        .init(number: 135, youtube: "0O6VgCqwUrs", daily: false,
              title: "when you want to be one of a kind", japanese: "天然記念物になりたいあなたに"),
        .init(number: 136, youtube: "zt9vzOmX0lY", daily: true,
              title: "when you think you bring the rain", japanese: "雨男＆雨女だと思っているあなたに"),
        .init(number: 137, youtube: "oBWk-pIpnmA", daily: false,
              title: "when you want a japanese heart", japanese: "和心でいたいあなたに"),
        .init(number: 138, youtube: "UCG38hnKAh0", daily: false,
              title: "when you're japan gold", japanese: "ジャパンゴールドのあなたにPart1"),
        .init(number: 139, youtube: "P9Kx9O_QmkY", daily: false,
              title: "when you don't know when to stop", japanese: "カットが聞こえないあなたに"),
        .init(number: 140, youtube: "2N3mwrX8eDA", daily: false,
              title: "when you're japan gold", japanese: "ジャパンゴールドのあなたにPart2"),
        .init(number: 141, youtube: "y5P3hiVMfnE", daily: true,
              title: "when you want to send energy", japanese: "元気を届けたいあなたに"),
        .init(number: 142, youtube: "iuwooeWXLMY", daily: true,
              title: "when the rain gets you down", japanese: "雨で憂鬱なあなたに"),
        .init(number: 143, youtube: "OxgvTT8PZtk", daily: false,
              title: "when you're part of lake biwa", japanese: "琵琶湖の一員なあなたに"),
        .init(number: 144, youtube: "rSiRjBVMr3E", daily: false,
              title: "when you're a london double-decker", japanese: "ロンドン2階建バスなあなたに"),
        .init(number: 145, youtube: "1gxc1ScSrhc", daily: true,
              title: "when every day is the olympics", japanese: "いつもオリンピックなあなたに"),
        .init(number: 146, youtube: "KJFDRFFZCuA", daily: false,
              title: "when you're not tired at all", japanese: "疲れはコナカった？なあなたに"),
        .init(number: 147, youtube: "Hi6jN0SH7Ew", daily: false,
              title: "when something clicks", japanese: "ハッとしてGOODなあなたに"),
        .init(number: 148, youtube: "xU-ZD-GUZWE", daily: false,
              title: "when you're the opening ceremony", japanese: "オープニングセレモニーなあなたに"),
        .init(number: 149, youtube: "YvLM_ajVFuc", daily: true,
              title: "when you're down", japanese: "倒れているあなたに"),
        .init(number: 150, youtube: "Ila-E5wlSL0", daily: true,
              title: "when you want to finish strong", japanese: "締めくくりたいあなたに"),
        .init(number: 151, youtube: "sO9W-04wC4A", daily: true,
              title: "when your heart is clean", japanese: "心が綺麗なあなたに"),
        .init(number: 152, youtube: "8r7l4dkcY_g", daily: true,
              title: "when you want a beautiful heart", japanese: "美しい心を持ちたいあなたに"),
        .init(number: 153, youtube: "4nIYigAzfjk", daily: false,
              title: "when you're a natural", japanese: "天然なあなたに"),
        .init(number: 154, youtube: "e4jBQVv3GHc", daily: true,
              title: "when you can't keep to time", japanese: "タイムリミットが守れないあなたに"),
        .init(number: 155, youtube: "Uu2qEZVYzsU", daily: false,
              title: "when you're autumn leaves", japanese: "もみじなあなたに"),
        .init(number: 156, youtube: "t3YEQ_UZSvc", daily: true,
              title: "when you can't show your feelings", japanese: "感情を表に出せないあなたに"),
        .init(number: 157, youtube: "qypT_QzyroQ", daily: true,
              title: "when your heart won't settle", japanese: "心が落ち着かないあなたに"),
        .init(number: 158, youtube: "JjWOIKyNDh0", daily: true,
              title: "when you can't picture your life", japanese: "自分の人生が描けていないあなたに"),
        .init(number: 159, youtube: "pVB5k0GZDJc", daily: false,
              title: "when you want someone in your corner", japanese: "我武者羅應援團に応援されたいあなたに"),
        .init(number: 160, youtube: "P7vnwLREprE", daily: true,
              title: "when you want to open up your luck", japanese: "運を開きたいあなたに"),
        .init(number: 161, youtube: "EI8eIePDbGE", daily: true,
              title: "when you want to get better", japanese: "上達したいあなたに"),
        .init(number: 162, youtube: "uQ5sMrYVIYo", daily: true,
              title: "when your ego is strong", japanese: "自我が強いあなたに"),
        .init(number: 163, youtube: "omOoyxcxhS0", daily: true,
              title: "when you can't find a purpose", japanese: "志を持てないあなたに"),
        .init(number: 164, youtube: "TKFuFYJrqK4", daily: true,
              title: "when the past drags you back", japanese: "過去に引きずられるあなたに"),
        .init(number: 165, youtube: "yzimf6CHkIU", daily: true,
              title: "when you're boxed in on every side", japanese: "八方ふさがりなあなたに"),
        .init(number: 166, youtube: "hZE7MCi9dLc", daily: false,
              title: "when you don't know what hot springs can do", japanese: "温泉の力を知らないあなたに"),
        .init(number: 167, youtube: "W-KXQHi2V0w", daily: true,
              title: "when you want to be the world's first", japanese: "世界初になりたいあなたに"),
        .init(number: 168, youtube: "B597ftyvsT8", daily: true,
              title: "when you don't want to be a bother", japanese: "迷惑をかけたくないあなたに"),
        .init(number: 169, youtube: "3JJ4noOlh2A", daily: true,
              title: "when you want to clear out the bad", japanese: "悪いものを取り除きたいあなたに"),
        .init(number: 170, youtube: "dP8kWZqqijQ", daily: true,
              title: "when a first try makes you nervous", japanese: "初めての挑戦で不安なあなたに"),
        .init(number: 171, youtube: "OFhie3YzXOw", daily: true,
              title: "when you want to shine", japanese: "輝きたいあなたに"),
        .init(number: 172, youtube: "JmXnXVLn96o", daily: true,
              title: "when you think no one trusts you", japanese: "誰からも信用されないあなたに"),
        .init(number: 173, youtube: "jPwNd1HslAs", daily: false,
              title: "when you love free space", japanese: "自由空間が好きなあなたに Part2"),
        .init(number: 174, youtube: "_rlD-LMXS2g", daily: true,
              title: "when you don't want to be a bother", japanese: "迷惑をかけたくないあなたに Part2"),
        .init(number: 175, youtube: "R8YTqp43-ss", daily: true,
              title: "when you want to fall for something", japanese: "惚れこみたいあなたに"),
        .init(number: 176, youtube: "oJPxpCVspfk", daily: true,
              title: "when you decide on looks alone", japanese: "見た目だけで決めちゃうあなたに"),
        .init(number: 177, youtube: "GGlnI8SX838", daily: true,
              title: "when you can't commit", japanese: "覚悟が持てないあなたに"),
        .init(number: 178, youtube: "8Hv4KzSKMHE", daily: false,
              title: "when you love free space", japanese: "自由空間が好きなあなたに"),
        .init(number: 179, youtube: "6YqmDwwKllE", daily: true,
              title: "when you need a warning", japanese: "警告が必要なあなたに"),
        .init(number: 180, youtube: "jVI6pHbrLf8", daily: true,
              title: "when you've lost your playfulness", japanese: "遊び心がないあなたに"),
        .init(number: 181, youtube: "zuaxdAVh_fI", daily: true,
              title: "when you're holding back", japanese: "自分を出し切れていないあなたに"),
        .init(number: 182, youtube: "lze_KIy9Uc0", daily: false,
              title: "when you've lost your fighting spirit", japanese: "ウルトラ魂がないあなたに"),
        .init(number: 183, youtube: "NaSzubYpIPg", daily: false,
              title: "when you want a bigger house", japanese: "もっと広い家に住みたいと思っているあなたに"),
        .init(number: 184, youtube: "wt7_r_zWJfQ", daily: false,
              title: "when you want to marry this summer", japanese: "今夏に結婚したいあなたに…"),
        .init(number: 185, youtube: "eOTyiGuab0g", daily: false,
              title: "when you really want to marry this summer", japanese: "やっぱりどーしても今夏に結婚したいあなたに…"),
        .init(number: 186, youtube: "ZQ7kn3w3nz0", daily: true,
              title: "when you want to value what makes you you", japanese: "個性を大事にしたいあなたに…"),
        .init(number: 187, youtube: "M_ESB38Z5BA", daily: true,
              title: "when your mood is cloudy", japanese: "気持ちが曇っているあなたに…"),
        .init(number: 188, youtube: "AFr6vfPZ9bI", daily: true,
              title: "when you can't finish things", japanese: "なかなか完成できないあなたに…"),
        .init(number: 189, youtube: "11Ui45XibA0", daily: false,
              title: "good evening", japanese: "ウルトラこんばんわのあなたにPart2"),
        .init(number: 190, youtube: "qoCt0um34Ic", daily: false,
              title: "when you're scared of dogs", japanese: "犬が恐いあなたに…"),
        .init(number: 191, youtube: "p07KJ1a_Z5M", daily: false,
              title: "good evening", japanese: "ウルトラこんばんわのあなたにPart1"),
        .init(number: 192, youtube: "N-cy2Uig-xE", daily: true,
              title: "when things don't go your way", japanese: "思うようにいかないあなたに"),
        .init(number: 193, youtube: "_CQQNSFhu7I", daily: true,
              title: "when you've forgotten how to be a kid", japanese: "子ども心を忘れてしまったあなたに"),
        .init(number: 194, youtube: "OrFmdCWg_zY", daily: true,
              title: "when you can't stop smirking", japanese: "ヘラヘラしちゃうあなたに…"),
        .init(number: 195, youtube: "3OOyJ36P6uw", daily: true,
              title: "when you only want convenience", japanese: "便利ばかり求めてしまうあなたに…"),
        .init(number: 196, youtube: "CQ3QKbDQ7zQ", daily: true,
              title: "when you mix up manners and rudeness", japanese: "礼儀と無礼をはき違えているあなたに"),
        .init(number: 197, youtube: "YfsXH0BFbBo", daily: false,
              title: "when you're obsessed with abroad", japanese: "外国にかぶれているあなたに"),
        .init(number: 198, youtube: "TbkBgTVxRjM", daily: true,
              title: "when you can't own what you do", japanese: "自分の行為に責任を持てないあなたに"),
        .init(number: 199, youtube: "l180zdsMqx4", daily: true,
              title: "when you've got it wrong", japanese: "勘違いしているあなたに…"),
        .init(number: 200, youtube: "Rs2s9_F7JTA", daily: true,
              title: "when you want big wings", japanese: "大きな翼がほしいあなたに…"),
        .init(number: 201, youtube: "Q-HZf-N8HKo", daily: true,
              title: "when you're fighting the devil inside", japanese: "心の悪魔と闘っているあなたに…"),
        .init(number: 202, youtube: "L6n90D5viw8", daily: true,
              title: "when you want to be an angel", japanese: "天使になりたいあなたに…"),
        .init(number: 203, youtube: "KIh2hjo-CnE", daily: false,
              title: "when you want to see rare medicinal food", japanese: "薬膳料理の特別食材を見たいあなたに"),
        .init(number: 204, youtube: "w22Z7ytY29I", daily: false,
              title: "when you want to see an emotional ski jumper", japanese: "喜怒哀楽スキージャンパーを見たいあなたに"),
        .init(number: 205, youtube: "iuFWx5VjhII", daily: true,
              title: "when you wonder what you even are", japanese: "自分はいったい何なんだろうと思っているあなたに"),
        .init(number: 206, youtube: "5bh5HPM3JRc", daily: false,
              title: "when you don't know why flying fish is so good", japanese: "「あご」の美味しさの秘密を知らないあなたに"),
        .init(number: 207, youtube: "nWseTyUTMGQ", daily: true,
              title: "when you want to rise", japanese: "コウヨウしたいあなたに"),
        .init(number: 208, youtube: "KWs1xy2CDtg", daily: true,
              title: "when you want to clear out a weak heart", japanese: "弱い心を消臭したいあなたに"),
        .init(number: 209, youtube: "aEQdesUJYY4", daily: true,
              title: "when you want to be the real thing", japanese: "こだわって本物になりたいあなたに"),
        .init(number: 210, youtube: "LuafIZdS7PA", daily: true,
              title: "when you hate the cold", japanese: "寒いのが嫌いなあなたに…"),
        .init(number: 211, youtube: "8PPuiu-_Hx8", daily: true,
              title: "when you want to listen with your heart", japanese: "心で聞きたいあなたに…"),
        .init(number: 212, youtube: "vXzh4Ey-1gQ", daily: true,
              title: "when you want to amaze people with something new", japanese: "新しい発明で人を驚かせたいあなたに"),
        .init(number: 213, youtube: "O7knii0-ALc", daily: true,
              title: "when you turn negative", japanese: "ネガティブになってしまうあなたに"),
        .init(number: 214, youtube: "PrPM6q_fwN4", daily: true,
              title: "when you feel no one understands you", japanese: "本当の気持ちを分かってくれないと思っているあなたに"),
        .init(number: 215, youtube: "tpiTQYl_r-s", daily: true,
              title: "when you're about to give up on your dream", japanese: "夢をあきらめそうなあなたに"),
        .init(number: 216, youtube: "bN0pFvrvKkQ", daily: true,
              title: "when your palms are sweating", japanese: "手に汗握るあなたに"),
        .init(number: 217, youtube: "VHDdE5a4mnc", daily: true,
              title: "when things don't turn out how you hoped", japanese: "思ったようにいなかいと思っているあなたに"),
        .init(number: 218, youtube: "UW_bjoMHpck", daily: true,
              title: "when you feel no one sees how hard you try", japanese: "頑張りを分かってくれないと思っているあなたに"),
        .init(number: 219, youtube: "BZ3SeFX4R-c", daily: true,
              title: "when you can't let go of common sense", japanese: "常識を捨てられないあなたに"),
        .init(number: 220, youtube: "xokJHwaPQwM", daily: true,
              title: "when you can't be yourself", japanese: "自分らしくいられないあなたに"),
        .init(number: 221, youtube: "Rqn5n5H9Z0k", daily: true,
              title: "when you think you can't", japanese: "できないと思っているあなたに"),
        .init(number: 222, youtube: "qe7IDacDKGE", daily: true,
              title: "when you need an on and an off", japanese: "ONとOFFが必要なあなたに…"),
        .init(number: 223, youtube: "feDbf3vJE4w", daily: true,
              title: "when you dwell on small things", japanese: "ちっぽけなことを考えてしまうあなたに…"),
        .init(number: 224, youtube: "eUQCNw20VKk", daily: false,
              title: "when you want to ride the narrow road", japanese: "細道に乗りたいあなたに…"),
        .init(number: 225, youtube: "1iJHYXp7u70", daily: true,
              title: "when connecting is as far as it goes", japanese: "つながったで終わってしまうあなたに"),
        .init(number: 226, youtube: "3mJubzRZcPQ", daily: false,
              title: "when you want to share a japanese heart", japanese: "和の心を伝えたいあなたに…"),
        .init(number: 227, youtube: "pYxyVEqa_Ls", daily: true,
              title: "when life won't move forward", japanese: "なかなか人生が進まないあなたに"),
        .init(number: 228, youtube: "6OFk3lhMhRQ", daily: true,
              title: "when you doubt everything", japanese: "疑い深いあなたに"),
        .init(number: 229, youtube: "Fu1I6vzrKas", daily: false,
              title: "when you want to get your message out", japanese: "発新力と発神力で発信力したいあなたに…"),
        .init(number: 230, youtube: "lbqdjod0Nz0", daily: true,
              title: "when you want a bouncing heart", japanese: "心を弾ませたいあなたに…"),
        .init(number: 231, youtube: "A7fhpu_ApDM", daily: true,
              title: "when you want to share a feeling", japanese: "だよねって想いを共感したいあなたに…"),
        .init(number: 232, youtube: "rGHOqISzRx8", daily: true,
              title: "when you want an exciting challenge", japanese: "ワクワクなチャレンジをしたいあなたに"),
        .init(number: 233, youtube: "UohuVYvo7rE", daily: true,
              title: "when you can't choose for yourself", japanese: "自分で選ぶことができないあなたに…"),
        .init(number: 234, youtube: "ZPtCRpL-vCs", daily: true,
              title: "when you really want to take on the world", japanese: "本気で世界を目指したいあなたに"),
        .init(number: 235, youtube: "jbJPYp2EH-E", daily: true,
              title: "when you want your dream to come true", japanese: "夢を叶えたいあなたに"),
        .init(number: 236, youtube: "Yh-ctq-dS4s", daily: true,
              title: "when you don't want to lose to adversity", japanese: "逆境に負けたくないあなたに"),
        .init(number: 237, youtube: "izdViQhwnls", daily: true,
              title: "when you want to walk with shuzo", japanese: "修造と一緒に歩みたいあなたに"),
        .init(number: 238, youtube: "NqdAFhzNFrI", daily: true,
              title: "when you want a challenge", japanese: "チャレンジしたいあなたに"),
        .init(number: 239, youtube: "7ARNIDCi2eE", daily: true,
              title: "when you're not feeling alive", japanese: "生き生きしていないあなたに"),
        .init(number: 240, youtube: "cCAT1t7LbSs", daily: false,
              title: "when you want to bloom", japanese: "はなっこりーになりたいあなたに"),
        .init(number: 241, youtube: "AKW_ezjmzrQ", daily: true,
              title: "when you can't believe in yourself", japanese: "自分が信じられないあなたに"),
        .init(number: 242, youtube: "oQKUsFsR-hE", daily: true,
              title: "when you want to be someone who can", japanese: "できる人になりたいあなたに"),
        .init(number: 243, youtube: "fyZkg9-4dm0", daily: true,
              title: "when you want to really cheer someone on", japanese: "本気で応援したいあなたに"),
        .init(number: 244, youtube: "fsdBNLBMCuo", daily: true,
              title: "when you've learned to focus", japanese: "集中力を学んだあなたに"),
        .init(number: 245, youtube: "j51QmaDAKvA", daily: true,
              title: "when you want to focus", japanese: "集中したいあなたに2"),
        .init(number: 246, youtube: "KJfDzs0Y24M", daily: true,
              title: "when you want to focus", japanese: "集中したいあなたに1"),
        .init(number: 247, youtube: "8gNOEybLULI", daily: true,
              title: "when you can't focus", japanese: "集中できないあなたに"),
        .init(number: 248, youtube: "RwgUycw4d-o", daily: true,
              title: "when you think you've got grit", japanese: "根性があると思っているあなたに"),
        .init(number: 249, youtube: "ystaJusmfD0", daily: true,
              title: "when you want to think for yourself", japanese: "「自分思考」になりたいあなたに"),
        .init(number: 250, youtube: "COrx4zuiPq8", daily: true,
              title: "when you live freely", japanese: "自由に生きているあなたに"),
        .init(number: 251, youtube: "fK-6xEI76FY", daily: true,
              title: "when you've got it wrong", japanese: "勘違いしているあなたに"),
        .init(number: 252, youtube: "9VQ4V3p5BdA", daily: true,
              title: "when you've been left out to dry", japanese: "干されているあなたに"),
        .init(number: 253, youtube: "zI31vS3zufI", daily: true,
              title: "when your feelings waver", japanese: "気持ちがブレているあなたに"),
        .init(number: 254, youtube: "uVtUjGHQRcY", daily: true,
              title: "when you think tradition is old-fashioned", japanese: "伝統を古くさいと思っているあなたに"),
        .init(number: 255, youtube: "O1A4b6xzihs", daily: false,
              title: "when you really want to go skiing", japanese: "本気でスキーに行きたいあなたに"),
        .init(number: 256, youtube: "cDPlEylPIh4", daily: true,
              title: "when things are too comfortable", japanese: "ぬるい環境にいるあなたに"),
        .init(number: 257, youtube: "INAimxPmcO8", daily: true,
              title: "when your heart is cold", japanese: "心が寒いあなたに"),
        .init(number: 258, youtube: "TNRhkU2zTFM", daily: true,
              title: "when you give off a bad vibe", japanese: "嫌な雰囲気を漂わせているあなたに"),
        .init(number: 259, youtube: "JG-XYv-j20c", daily: true,
              title: "when you want to be reborn", japanese: "生まれ変わりたいあなたに"),
        .init(number: 260, youtube: "EpYSEOnArzE", daily: true,
              title: "when you've failed", japanese: "失敗してしまったあなたに"),
        .init(number: 261, youtube: "5IYuNQZgslI", daily: true,
              title: "when you think you're alone", japanese: "一人だと思っているあなたに"),
        .init(number: 262, youtube: "IoWjHHrr1Nw", daily: true,
              title: "when you don't take care of yourself", japanese: "自分に手間をかけていないあなたに"),
        .init(number: 263, youtube: "ymZLdnboVoI", daily: false,
              title: "when you can't hold your drink", japanese: "お酒に弱いあなたに"),
        .init(number: 264, youtube: "uDHUPVhs4F0", daily: false,
              title: "when you're one of a kind", japanese: "Special Priceなあなたに"),
        .init(number: 265, youtube: "Bd8V8nb6Ym0", daily: true,
              title: "when you can't get back to basics", japanese: "初心に戻れないあなたに"),
        .init(number: 266, youtube: "9DYHGotLAwc", daily: true,
              title: "when you can't keep going", japanese: "継続できないあなたに"),
        .init(number: 267, youtube: "YHXA5oDVR2I", daily: true,
              title: "when you decide by appearances", japanese: "外見で決めてしまうあなたに"),
        .init(number: 268, youtube: "4fexRP6bj8k", daily: true,
              title: "when things aren't going well with people", japanese: "人とうまくいってないあなたに"),
        .init(number: 269, youtube: "Y1ra8-sHws8", daily: false,
              title: "when you want to float", japanese: "浮きたい！と思っているあなたに…"),
        .init(number: 270, youtube: "Oi3uBAXpkH4", daily: false,
              title: "when you want to unwind after work", japanese: "「だれやめ」したいあなたに…"),
        .init(number: 271, youtube: "XA8ON8mfglk", daily: false,
              title: "when you really want to live in quebec", japanese: "本気でケベックに住みたいと思っているあなたに…"),
        .init(number: 272, youtube: "IGPOMDfCSTQ", daily: true,
              title: "when you're ready to leap", japanese: "Hop Step Jumpなあなたに…"),
        .init(number: 273, youtube: "tPsmss3ZUO8", daily: true,
              title: "when you think you can't jump", japanese: "跳べないと思っているあなたに…"),
        .init(number: 274, youtube: "ph0onzDCd8o", daily: true,
              title: "when you wonder if going this far means anything", japanese: "ここまでやって意味があるのか？と思っているあなたに…"),
        .init(number: 275, youtube: "thXhFudRakU", daily: true,
              title: "when you can't ask what you forgot", japanese: "忘れたことを聞けずにいるあなたに…"),
        .init(number: 276, youtube: "c8GbGWWFvlk", daily: true,
              title: "when your spirits won't lift", japanese: "気持ちが上を向かないあなたに"),
        .init(number: 277, youtube: "N4JV4wihKI4", daily: true,
              title: "when your heart won't settle", japanese: "心が落ち着かないあなたに"),
        .init(number: 278, youtube: "IyJHv6O9u1I", daily: true,
              title: "when you want to change your heart's colour", japanese: "心の色を変えたいあなたに"),
        .init(number: 279, youtube: "a_B17VRaeUg", daily: true,
              title: "when you want to be number one", japanese: "1番になりたいあなたに Part1"),
        .init(number: 280, youtube: "Q-HZT8rDOVM", daily: true,
              title: "when you're sinking", japanese: "沈んでいるあなたに…"),
        .init(number: 281, youtube: "p8B_KnWAHTE", daily: true,
              title: "when you have a weak side", japanese: "「弱さ」があるあなたに"),
        .init(number: 282, youtube: "R6VJbdEPsH8", daily: true,
              title: "when you decide by appearances", japanese: "見かけで決めてしまうあなたに…"),
        .init(number: 283, youtube: "jGKK3oRDiQQ", daily: true,
              title: "when you want to run it all the way", japanese: "走りきりたいあなたに…"),
        .init(number: 284, youtube: "l6NBTWTY4cU", daily: true,
              title: "when you think you're taking it easy", japanese: "楽をしていると思っているあなたに"),
        .init(number: 285, youtube: "KzQB0HlUGRM", daily: false,
              title: "when it's your birthday", japanese: "誕生日なあなたに"),
        .init(number: 286, youtube: "VH9LDJ3AwHY", daily: true,
              title: "when you tend to sink", japanese: "沈みがちなあなたに"),
        .init(number: 287, youtube: "VhQKIcT4nZw", daily: true,
              title: "when you're trying to get serious", japanese: "本気になろうとしているあなたに"),
        .init(number: 288, youtube: "MT_-YWe9Wxk", daily: false,
              title: "when you get angry", japanese: "イカってしまうあなたに"),
        .init(number: 289, youtube: "M2pKNgh-ZDI", daily: false,
              title: "when you want a handshake", japanese: "修ちゃんと握手したいあなたに"),
        .init(number: 290, youtube: "Z2bGJiTo2N4", daily: true,
              title: "when you judge people by their looks", japanese: "人を見かけで判断してしまうあなたに"),
        .init(number: 291, youtube: "Ry9iqHZDpRc", daily: true,
              title: "when you have no colour of your own", japanese: "自分の色がないあなたに"),
        .init(number: 292, youtube: "pR9Xqw2uVHE", daily: true,
              title: "when you always walk along the edges", japanese: "はじっこばかり歩いているあなたに"),
        .init(number: 293, youtube: "l3uroy79jqM", daily: false,
              title: "when you want to be serious in the toilet", japanese: "トイレで本気を伝えたいあなたに"),
        .init(number: 294, youtube: "q8UMwH6umlA", daily: false,
              title: "when you want to be moved by a toilet", japanese: "トイレに感動したいあなたに"),
        .init(number: 295, youtube: "mqBB3d-8fD8", daily: true,
              title: "when you can't live in the now", japanese: "今を生きれないあなたに…"),
        .init(number: 296, youtube: "Kp_Q_Q-Qplg", daily: true,
              title: "when you're living on the surface", japanese: "上っ面だけで生きているあなたに"),
        .init(number: 297, youtube: "vzw6DgU7JK8", daily: true,
              title: "when you're not no good", japanese: "ダメじゃないあなたに"),
        .init(number: 298, youtube: "rWRkTpevQ2Q", daily: true,
              title: "when looks make you give up", japanese: "見た目で諦めてしまうあなたに"),
        .init(number: 299, youtube: "ydW4Qm-Q2Sc", daily: true,
              title: "when you push yourself forward too much", japanese: "出しゃばってしまうあなたに"),
        .init(number: 300, youtube: "aaGRFxbDJC0", daily: true,
              title: "when you have no focus", japanese: "集中力のないあなたに"),
        .init(number: 301, youtube: "3SNLPEcdh5M", daily: true,
              title: "when you're stuck in fixed ideas", japanese: "固定観念を持っているあなたに"),
        .init(number: 302, youtube: "JKviKHfoNyA", daily: true,
              title: "when you think you've lost everything", japanese: "すべてを失ったと思っているあなたに"),
        .init(number: 303, youtube: "Bqm5ZYYLlIc", daily: true,
              title: "when you think you're disliked", japanese: "嫌われていると思っているあなたに"),
        .init(number: 304, youtube: "5eSKUDzQreU", daily: true,
              title: "when you can't live fair and square", japanese: "正々堂々と生きられないあなたに"),
        .init(number: 305, youtube: "7WhJvR24Ma8", daily: true,
              title: "when your surroundings overwhelm you", japanese: "周りの環境に圧倒されてしまうあなたに"),
        .init(number: 306, youtube: "tAzQQDwQCZE", daily: true,
              title: "when you can't believe nothing is impossible", japanese: "不可能なんてないと思えないあなたに"),
        .init(number: 307, youtube: "l73mdL_nDFc", daily: true,
              title: "when you judge by appearances", japanese: "見た目で判断してしまうあなたに"),
        .init(number: 308, youtube: "C-lA8JjKGpc", daily: true,
              title: "when you can't get serious", japanese: "本気になれないあなたに"),
        .init(number: 309, youtube: "mmUnquz-rdM", daily: false,
              title: "when you want festival music to make your heart dance", japanese: "祭りばやしでこころを踊らせたいあなたに"),
        .init(number: 310, youtube: "eM6A8SjJQG0", daily: true,
              title: "when you think you'll never get ahead", japanese: "出世できないと思っているあなたに"),
        .init(number: 311, youtube: "mbu3AIKk2qQ", daily: true,
              title: "when another day is done", japanese: "今日もおわったと思ったあなたに"),
        .init(number: 312, youtube: "99_GG3uvHLI", daily: true,
              title: "when you lack imagination", japanese: "想像力の足りないあなたに"),
        .init(number: 313, youtube: "4lZrGulru_A", daily: true,
              title: "when exams are finally here", japanese: "いよいよ受験！のあなたに"),
        .init(number: 314, youtube: "HP_WeboHsVI", daily: true,
              title: "when you want to change the world", japanese: "世界を変えたいあなたに①"),
        .init(number: 315, youtube: "8FNWAb3LL9E", daily: true,
              title: "when you want to change the world", japanese: "世界を変えたいあなたに②"),
        .init(number: 316, youtube: "SjwJqJrq6dA", daily: true,
              title: "when you think no one will protect you", japanese: "誰も守ってくれないと思っているあなたに"),
        .init(number: 317, youtube: "-nbqA2N3EBs", daily: true,
              title: "when you can't like yourself", japanese: "自分を好きになれないあなたに"),
        .init(number: 318, youtube: "eD7bVmKyJ94", daily: true,
              title: "when you want to win", japanese: "勝負に勝ちたいあなたに"),
        .init(number: 319, youtube: "HovI4JykeFo", daily: true,
              title: "when you hate failing", japanese: "失敗がイヤなあなたに"),
        .init(number: 320, youtube: "dVPWjCJzi6E", daily: true,
              title: "when you've lost your way", japanese: "自分の行く道がわからなくなったあなたに…"),
        .init(number: 321, youtube: "crEu66AwS9A", daily: true,
              title: "when you're giving up on your dream", japanese: "夢をあきらめようとしているあなたに"),
        .init(number: 322, youtube: "Vmol4aVfaQg", daily: true,
              title: "when you keep clashing", japanese: "ぶつかり合ってしまうあなたに"),
        .init(number: 323, youtube: "vrLkoy6kdFs", daily: true,
              title: "when you can't chase your goal your own way", japanese: "自分らしく目標を目指せないあなたに"),
        .init(number: 324, youtube: "LbfnxHBRMo8", daily: true,
              title: "when hearts can't come together", japanese: "心が一つになれないあなたに"),
        .init(number: 325, youtube: "1D92_zb6uMg", daily: true,
              title: "when you can't get your feelings across", japanese: "想いを伝えられないあなたに"),
        .init(number: 326, youtube: "6OVR-lWeGPE", daily: true,
              title: "when people are counting on you", japanese: "期待をかけられているあなたに"),
        .init(number: 327, youtube: "CoP2y4C9YQk", daily: true,
              title: "when you can't be yourself", japanese: "自分らしくいられないあなたに"),
        .init(number: 328, youtube: "ormRvwhJwz8", daily: true,
              title: "when your heart feels small", japanese: "心がちっぽけなあなたに"),
        .init(number: 329, youtube: "I8U7Hyw3WYo", daily: false,
              title: "when you want to eat to win", japanese: "EAT TO WINしたいあなたに"),
        .init(number: 330, youtube: "lcIjE-CqwsY", daily: true,
              title: "when you can't surprise anyone", japanese: "サプライズできないあなたに"),
        .init(number: 331, youtube: "tLV1G3-mSwk", daily: true,
              title: "when you think it's always the same", japanese: "いつも同じだと思っているあなたに"),
        .init(number: 332, youtube: "Rz_kYBPYgsI", daily: true,
              title: "when you want to feel something", japanese: "何かを感じたいあなたに"),
        .init(number: 333, youtube: "S5kXu_hZMAU", daily: true,
              title: "when you give up halfway", japanese: "途中であきらめてしまうあなたに"),
        .init(number: 334, youtube: "rHOKTOKVg-U", daily: true,
              title: "when you can't fire people up", japanese: "人を熱くできないあなたに"),
        .init(number: 335, youtube: "JGlX7JjnV7Q", daily: true,
              title: "when you want to be reborn as a new you", japanese: "新しい自分に生まれ変わりたいあなたに。"),
        .init(number: 336, youtube: "a5yGF8dRe1Y", daily: false,
              title: "when you want to stand tall", japanese: "姿勢天使シャーン造になりたいあなたに"),
        .init(number: 337, youtube: "DDWV1n6xOIo", daily: true,
              title: "when you want to be like an angel", japanese: "天使のようになりたいあなたに"),
        .init(number: 338, youtube: "JPTbd5whMSw", daily: true,
              title: "when you want a clear heart", japanese: "きれいな心を持ちたいあなたに"),
        .init(number: 339, youtube: "Wo9WbkIWvis", daily: true,
              title: "when you can't control yourself", japanese: "自分をコントロールできないあなたに"),
        .init(number: 340, youtube: "AmVpWEa4W30", daily: true,
              title: "when you're anxious on the edge", japanese: "崖っぷちで不安を感じているあなたに"),
        .init(number: 341, youtube: "us8pTZrC3EA", daily: true,
              title: "when you're on the edge", japanese: "崖っぷちにいるあなたに"),
        .init(number: 342, youtube: "w3_Wjvxdqp0", daily: true,
              title: "when you worry what people think", japanese: "人の評価を気にしてしまうあなたに"),
        .init(number: 343, youtube: "-_3Bi-1fHTw", daily: true,
              title: "when you can't wipe out a weak heart", japanese: "弱い心を滅れないあなたに"),
        .init(number: 344, youtube: "KjOr5barw04", daily: true,
              title: "when you give up", japanese: "諦めてしまうあなたに"),
        .init(number: 345, youtube: "nHfsuBdOczE", daily: true,
              title: "when you're too busy to know what to do", japanese: "忙しくて何をすればいいか分からないあなたに"),
        .init(number: 346, youtube: "BjCn0WaHUuw", daily: true,
              title: "when you're just drifting through the days", japanese: "なんとなく毎日過ごしちゃってるあなたに"),
        .init(number: 347, youtube: "ucJ6C9E5s24", daily: true,
              title: "when you're taking things too seriously", japanese: "気持ちが深刻になりすぎているあなたに"),
        .init(number: 348, youtube: "S6lBaxSohW8", daily: true,
              title: "when you can't enjoy imagining", japanese: "想像を楽しめないあなたに"),
        .init(number: 349, youtube: "G7rIUihXajU", daily: true,
              title: "when you think nothing ever goes right", japanese: "うまくいかないことばかりと思っているあなたに"),
        .init(number: 350, youtube: "OwwWyazU2xk", daily: true,
              title: "when you can't get serious", japanese: "本気になれないあなたに"),
        .init(number: 351, youtube: "eZgTG01dhTc", daily: true,
              title: "when you think you don't matter", japanese: "自分は意味がないと思っているあなたに"),
        .init(number: 352, youtube: "hySSRHwTiIM", daily: true,
              title: "when you can't picture it", japanese: "イメージできないあなたに"),
        .init(number: 353, youtube: "qkC6_BH0Ny4", daily: true,
              title: "when you want to be happy", japanese: "し泡せになりたいあなたに"),
        .init(number: 354, youtube: "RepaSkdVXZc", daily: true,
              title: "when you want to be like a flower", japanese: "花のようになりたいあなたに"),
        .init(number: 355, youtube: "NdcAYT-FUHM", daily: true,
              title: "when you're caught in a negative spiral", japanese: "ネガティブな渦の中にいるあなたに"),
    ]
}
