// Generated from Support/inspo.json by scripts/make-inspo.sh. Don't edit.
// Inspo.Video(number, youtube id, in the daily rotation, english, original title)

package io.github.mmerioles.drill.core

internal val INSPO_VIDEOS = listOf(
    Inspo.Video(1, "KxGRhd_iWuE", true, "never give up", "あきらめかけているあなた"),
    Inspo.Video(2, "AO8RNNxEAjM", true, "when you can't get motivated", "やる気が起きないあなたに"),
    Inspo.Video(3, "cqroRiHMGLs", true, "when you keep saying you can't", "無理とか出来ないとか言っちゃうあなたに"),
    Inspo.Video(4, "9LRmzqZ6sXI", true, "when looks fool you", "見かけに騙されちゃうあなたに"),
    Inspo.Video(5, "I9UFRHgdOBQ", false, "when you want to win at look-that-way", "そっち向いてホイッ！で勝ちたいあなたに"),
    Inspo.Video(6, "Frar_GMjR6M", true, "when you can't believe in yourself", "自信が持てないあなたに"),
    Inspo.Video(7, "Bt1Q47D6Xh8", true, "when you can't give it everything", "出しきれないあなたに"),
    Inspo.Video(8, "Hw2q1lKio8g", true, "when you can't feel anything", "何かを感じれないあなたに"),
    Inspo.Video(9, "FbhSpnA3FEU", false, "when your meals don't satisfy you", "食事に満足できないあなたに"),
    Inspo.Video(10, "M0eL-jttkEw", true, "when you're stuck in fixed ideas", "固定観念を持っているあなたに"),
    Inspo.Video(11, "xXfJ5OcaiIQ", true, "when you can't let things go", "サバサバできないあなたに"),
    Inspo.Video(12, "Rtugrnveonw", false, "when you want to feel french", "フランス語を感じたいあなたに"),
    Inspo.Video(13, "Pgnnsjh5a4M", false, "when you can't make small talk", "トークができないあなたに"),
    Inspo.Video(14, "7RH1QD6RUJM", false, "when you want to feel france", "フランスを感じたいあなたに"),
    Inspo.Video(15, "am2mNGirfEE", false, "when you want to feel nature", "ネイチャーに感じたいあなたにPart5"),
    Inspo.Video(16, "fax4dK7sRbU", false, "when you want to feel nature", "ネイチャーを感じたいあなたにPart１"),
    Inspo.Video(17, "cRcCktNTak0", true, "when you keep looking back", "過去ばかり振り返ってしまうあなたに"),
    Inspo.Video(18, "aPoi08LD2-c", false, "when you want to feel nature", "ネイチャーを感じたいあなたにPart2"),
    Inspo.Video(19, "1AkuN0IGsiU", false, "when you want to feel nature", "ネイチャーを感じたいあなたにPart3"),
    Inspo.Video(20, "-l70T7qvZ6g", true, "when you can't take a step forward", "一歩前に進めないあなたに"),
    Inspo.Video(21, "LABoKsMTOIc", false, "when you want to feel nature", "ネイチャーを感じたいあなたにPart4"),
    Inspo.Video(22, "1D_pDimyIhw", true, "when you can't take a fall well", "上手に受け身ができないあなたに"),
    Inspo.Video(23, "q7L_ZpAm8sI", true, "when you want to get serious", "本気になりたいあなたに"),
    Inspo.Video(24, "AXnJODC3XrQ", true, "when you can't be yourself", "自分らしさを出せないあなたに"),
    Inspo.Video(25, "13e7xiMrRJg", true, "when traffic gets to you", "渋滞にイライラするあなたに"),
    Inspo.Video(26, "aoAiSd-8-mI", true, "when the rain gets you down", "雨で憂鬱なあなたに"),
    Inspo.Video(27, "ZvhXyrBuJ-E", false, "when you want your suit fresh every day", "スーツを毎日フレッシュに着たいあなたに"),
    Inspo.Video(28, "NjcG5RiMJNc", true, "when you can't say thank you", "ありがとうが言えないあなたに"),
    Inspo.Video(29, "jl4ZwOfuIXQ", true, "when you're fighting sleep", "睡魔と格闘しているあなたにPart3"),
    Inspo.Video(30, "VFJcn2x1OGw", true, "when you're fighting sleep", "睡魔と格闘しているあなたにPart4"),
    Inspo.Video(31, "Qy-fn7cXim0", true, "when you're fighting sleep", "睡魔と格闘しているあなたにPart5"),
    Inspo.Video(32, "yS6QvC1S9Cc", true, "when you can't say your thanks out loud", "感謝の気持ちを口に出せないあなたに"),
    Inspo.Video(33, "tmqagdoQfM4", true, "when you're fighting sleep", "睡魔と格闘しているあなたにPart2"),
    Inspo.Video(34, "rStCUXOB0TI", true, "when you're fighting sleep", "睡魔と格闘しているあなたにPart1"),
    Inspo.Video(35, "zbaFP2CQk-Q", true, "when you want to go for gold", "ゴールドになりたいあなたに…"),
    Inspo.Video(36, "nzmzu7ofzCw", true, "when you're giving it your all", "一所懸命頑張っているあなたに"),
    Inspo.Video(37, "kwl-PZMYx3U", true, "when you think you can live alone", "一人で生きられるあなたに…"),
    Inspo.Video(38, "K8TYE26eAz8", false, "when you want to be a good listener", "徹子の部屋なあなたに"),
    Inspo.Video(39, "IRVxpdz7xJQ", true, "when you're shallower than tea", "お茶のように深みのないあなたに…"),
    Inspo.Video(40, "3XJJ44YfRQQ", true, "when you want to shine", "輝きたいあなたに"),
    Inspo.Video(41, "iZW-biK8YBE", true, "when you fidget and hold back", "もじもじしちゃうあなたに…"),
    Inspo.Video(42, "ShW4ZbacgIc", true, "when you only notice the shadows", "影ばかり気にしてしまうあなたに…"),
    Inspo.Video(43, "fcxIonI6Xic", true, "when you're shy", "恥ずかしがり屋のあなたに…"),
    Inspo.Video(44, "VCOT1BbeoLk", true, "when you judge people by their looks", "人を見かけで判断してしまうあなたに…"),
    Inspo.Video(45, "KDQ5NI3eXQ0", true, "when you want to say how you feel", "想いを伝えたいあなたに…スペイン編"),
    Inspo.Video(46, "5TFy5KZairo", true, "when you can't wait", "待てないあなたに"),
    Inspo.Video(47, "1sYTUWuyl4Y", false, "when you need cheering up", "くまもんに元気をもらいたいあなたに…"),
    Inspo.Video(48, "t7NYfo67cDc", true, "when you want to let nature take you", "自然に身をゆだねたいあなたに"),
    Inspo.Video(49, "fdln38t6Nko", false, "when you want depth", "お茶のように渋くなりたいあなたに…"),
    Inspo.Video(50, "DLaedW-NrOc", true, "when you want to go with the flow", "川の流れに身を任せたいあなたに"),
    Inspo.Video(51, "y-1OAIA1mwk", true, "when you've got it wrong", "勘違いしているあなたに"),
    Inspo.Video(52, "uI-gVhENee0", true, "when you want to start together", "みんなでスタートしたいあなたに"),
    Inspo.Video(53, "SVfuSsXPSbc", true, "when you don't want to bounce off", "跳ね返されたくないあなたに"),
    Inspo.Video(54, "f5OMGQW4v-E", true, "when you think half-hearted is bad", "中途半端がダメだと思っているあなたに…"),
    Inspo.Video(55, "IlE5AE6XU6o", true, "when you can't feel what others feel", "人の思いを感じられないあなたに"),
    Inspo.Video(56, "8BNNbXnnLMM", false, "when you want to spin round and round", "ぐるぐる回りたいあなたに"),
    Inspo.Video(57, "8wJYOBzZoFs", true, "when you can't enjoy yourself anywhere", "どこでも楽しめないあなたに…"),
    Inspo.Video(58, "13Hsr2cWU2o", true, "when you're lost for what to do", "戸惑ってしまうあなたに…"),
    Inspo.Video(59, "PdBlee8ZPX4", true, "when images sway you", "イメージに左右されているあなたに…"),
    Inspo.Video(60, "Fz3jcYe8oCU", true, "when your heart is in a black hole", "心がブラックホールにいるあなたに"),
    Inspo.Video(61, "CrvPZD3cT4w", false, "when you're tired of saying good work", "お疲れさまですに疑問を感じているあなたに…"),
    Inspo.Video(62, "A9K3UciyyPQ", true, "when you can't live in the now", "今を生きれないあなたに"),
    Inspo.Video(63, "9T8kvWbzp0c", true, "when you want to get along with everyone", "みんなと仲良くしたいあなたに"),
    Inspo.Video(64, "eufHdd1gGGI", false, "when you want to draw people in", "マグネットパワーインされたいあなたに"),
    Inspo.Video(65, "--SiDaFM2h0", true, "when you're not fighting yourself", "自分と戦えていないあなたに"),
    Inspo.Video(66, "QViVWFS10Hc", true, "when you can't believe in yourself", "自信が持てないあなたに…感謝祭ver"),
    Inspo.Video(67, "ACzESLeff3s", true, "when you're bad at getting things across", "伝えることが苦手なあなたに…"),
    Inspo.Video(68, "J-Scu0O23R0", true, "when you want to cheer yourself up", "自分を元気づけたいあなたに"),
    Inspo.Video(69, "a568Txh1CJU", true, "when you can't make up your mind", "なかなか決めれないあなたに…"),
    Inspo.Video(70, "YjuVqJ1fS-M", true, "when you're anxious about what's next", "今後の自分が不安なあなたに…"),
    Inspo.Video(71, "UTTDhe_b0sA", true, "when you want to become a legend", "伝説になりたいあなたに"),
    Inspo.Video(72, "HfiwfNqd5Bo", false, "when things feel good", "気持ちいいな～と思っているあなたに"),
    Inspo.Video(73, "QNTeB0czkXA", true, "you're a world heritage site too", "あなたも世界遺産！"),
    Inspo.Video(74, "AoUr_B5fM4c", true, "when you're hungry for it", "Hungryに応援したいあなたに"),
    Inspo.Video(75, "ipefkerDosY", false, "when you want to feel tradition", "伝統を感じたいあなたに…"),
    Inspo.Video(76, "EZuQKc8dUg0", true, "when you want to give others courage", "勇気を与えられる人になりたいあなたに…"),
    Inspo.Video(77, "vhtYLkWGuxM", true, "when you're about to give up", "できないと諦めそうなあなたに…"),
    Inspo.Video(78, "3V57MIc9hEs", true, "when you can't give it everything", "出しきれないあなたに…"),
    Inspo.Video(79, "FVn6s6PvDT8", true, "when you want to keep a calm heart", "心を冷静に保ちたいあなたに…"),
    Inspo.Video(80, "4z8z12rOhq4", true, "when you want to cry it all out", "涙を出しきりたいあなたに…"),
    Inspo.Video(81, "cI8N0oUhXz8", false, "when you want to feel sports culture", "スポーツ文化を感じたいあなたに…"),
    Inspo.Video(82, "eg-Nk_lLcEs", false, "when you like oranges", "オレンジが好きなあなたに…"),
    Inspo.Video(83, "ahDxH2PU8qk", true, "when you want your dream to come true", "夢を叶えたいあなたに"),
    Inspo.Video(84, "-EBBTBqcA2U", true, "when you're selfish", "わがままなあなたに"),
    Inspo.Video(85, "xhL4RG-mrV4", true, "when you don't want to stop", "止まりたくないあなたに…"),
    Inspo.Video(86, "2JuKqgcSHyE", true, "when you can't lay it all bare", "全てをさらけ出せないあなたに…"),
    Inspo.Video(87, "6eKkzgEywvI", true, "when you miss what matters right in front of you", "目の前の大事なものに気づけていないあなたに"),
    Inspo.Video(88, "XPrXCVc57vA", true, "when your heart is scattered", "心が散っているあなたに"),
    Inspo.Video(89, "seExlemsTu0", false, "when you want to start over", "ハリー・ポッターでリボーンしたいあなたに"),
    Inspo.Video(90, "lzirT7ahGg8", true, "when your heart is weak", "心が弱いあなたに"),
    Inspo.Video(91, "tnMRoyVdxmA", true, "when you can't open up", "心が開けないあなたに"),
    Inspo.Video(92, "TdsL7hYmc94", true, "when you can't move forward", "前に進めないあなたに"),
    Inspo.Video(93, "O1JEm3GTgy0", true, "when your heart is in full bloom", "心が満開のあなたに"),
    Inspo.Video(94, "FQMX48sgMMQ", true, "when you want to be number one", "1位になりたいあなたに"),
    Inspo.Video(95, "Kxt_S-JKoew", true, "when you want to feel better", "元気になりたいあなたに"),
    Inspo.Video(96, "Kozb9ZtUdMs", true, "when you want real strength", "本気の強さを持ちたいあなたに"),
    Inspo.Video(97, "CPQkgr7JYWg", false, "when you're not scared of bears", "熊が怖くないあなたに"),
    Inspo.Video(98, "0GFuP7PKsYk", true, "when you want a gold medal mind", "金メンタリストになりたいあなたに"),
    Inspo.Video(99, "Ylgy4ZTQTwE", true, "when you want to meet a new you", "新しい自分に出会いたいあなたへ"),
    Inspo.Video(100, "DkmknQEej7w", true, "when you want results right away", "すぐに結果を出したがるあなたへ"),
    Inspo.Video(101, "5soMHmWxZn4", true, "when your heart wavers", "心がぶれちゃうあなたに"),
    Inspo.Video(102, "kEGQuvDRZfI", true, "when you think nothing good happens", "いいことないと思っているあなたに"),
    Inspo.Video(103, "YCNcq6W9cGA", true, "when you want to shine like a rainbow", "虹のように輝きたいあなたに"),
    Inspo.Video(104, "EHyCgvvJ0HA", true, "when you want to grow up tough", "わんぱくでもいい、たくましく育ちたいあなたへ"),
    Inspo.Video(105, "D_xot4jhwK8", true, "when you can't stand tall as yourself", "自分らしく堂々とできないあなたに"),
    Inspo.Video(106, "weU2gHWuXKU", true, "when you want to smile", "笑顔になりたいあなたに"),
    Inspo.Video(107, "oHcf-E4nL7E", true, "when you can't smile", "笑顔ができないあなたに"),
    Inspo.Video(108, "lKAEpXcurTo", true, "when you want to take it on with a smile", "笑顔で挑みたいあなたに"),
    Inspo.Video(109, "mOwil4iifO8", true, "when you can't get your feelings across", "自分の思いを伝えられないあなたに"),
    Inspo.Video(110, "jeE-_Q5zx60", true, "when you can't laugh", "笑えないあなたに"),
    Inspo.Video(111, "bW_12K63VRM", true, "when you're studying for exams", "受験生のあなたに"),
    Inspo.Video(112, "Z3kuHtAfKow", true, "when you think you can do it all alone", "自分一人で何でもできると思っているあなたに"),
    Inspo.Video(113, "9bHdIgsR-mA", true, "when you think you don't stand out", "自分は目立たないと思っているあなたに"),
    Inspo.Video(114, "QpAJUR7p_No", true, "when you take being alive for granted", "生きていることが当たり前だと思っているあなたに"),
    Inspo.Video(115, "ByKU3mF8mLI", false, "when you want to hear you can do it", "テゥ・プ・ル・フェルして欲しいあなたに"),
    Inspo.Video(116, "5ATdeqbLtDw", true, "when you want to say how you feel", "思いを伝えたいあなたに"),
    Inspo.Video(117, "5e7unFhiD_M", true, "when worry stops you trying", "不安でチャレンジできないあなたに"),
    Inspo.Video(118, "4a0RQY5yzgw", true, "when you really want to smile", "どーしても笑顔になりたいあなたに"),
    Inspo.Video(119, "AIccKhuwKsI", true, "when you're studying for exams", "受験生のあなたに03"),
    Inspo.Video(120, "ldWdjelof-g", true, "when your heart is weak", "心が弱いあなたに"),
    Inspo.Video(121, "ioCshGZKf4I", true, "when you can't lay it all bare", "すべてをさらけ出せないあなたに"),
    Inspo.Video(122, "P2GNhcawrfI", true, "when you're studying for exams", "受験生のあなたに01"),
    Inspo.Video(123, "25vtPJrLq4I", true, "when you're studying for exams", "受験生のあなたに02"),
    Inspo.Video(124, "0_wY-DV2ceY", true, "when you let your guard down", "脇が甘いあなたに"),
    Inspo.Video(125, "vMz-rBzJkww", true, "when your heart is cold", "心が寒いあなたに…"),
    Inspo.Video(126, "s0cZRIQflNM", true, "when you think you can't be a champion", "チャンピオンになれないと思っているあなたに…"),
    Inspo.Video(127, "Qj6XQMa4jUE", true, "when you keep complaining", "いたいようって言っちゃうあなたに"),
    Inspo.Video(128, "4eiKa6GVgYc", true, "when you think your surroundings aren't good enough", "良い環境がないと思っているあなたに"),
    Inspo.Video(129, "-QmpPswdXWc", true, "when you're waiting for something good to happen", "いいことないかなぁと思っているあなたに"),
    Inspo.Video(130, "uhgpiWS1130", true, "when your heart is scattered", "心が散っちゃったあなたに"),
    Inspo.Video(131, "Yag0KMbWNl8", false, "when you want to watch like the french", "フランス人のようにおしゃれに観戦したいあなたに"),
    Inspo.Video(132, "tyfaN_5a2Z8", true, "when you want to stand at the center", "センターに立ちたいと思っているあなたに"),
    Inspo.Video(133, "2oPT5vxcaV0", true, "when you're at the center", "センターに立ったあなたに"),
    Inspo.Video(134, "GTXt3NLnoHg", true, "when the rain makes you sulk", "雨（？）ったれているあなたに"),
    Inspo.Video(135, "0O6VgCqwUrs", false, "when you want to be one of a kind", "天然記念物になりたいあなたに"),
    Inspo.Video(136, "zt9vzOmX0lY", true, "when you think you bring the rain", "雨男＆雨女だと思っているあなたに"),
    Inspo.Video(137, "oBWk-pIpnmA", false, "when you want a japanese heart", "和心でいたいあなたに"),
    Inspo.Video(138, "UCG38hnKAh0", false, "when you're japan gold", "ジャパンゴールドのあなたにPart1"),
    Inspo.Video(139, "P9Kx9O_QmkY", false, "when you don't know when to stop", "カットが聞こえないあなたに"),
    Inspo.Video(140, "2N3mwrX8eDA", false, "when you're japan gold", "ジャパンゴールドのあなたにPart2"),
    Inspo.Video(141, "y5P3hiVMfnE", true, "when you want to send energy", "元気を届けたいあなたに"),
    Inspo.Video(142, "iuwooeWXLMY", true, "when the rain gets you down", "雨で憂鬱なあなたに"),
    Inspo.Video(143, "OxgvTT8PZtk", false, "when you're part of lake biwa", "琵琶湖の一員なあなたに"),
    Inspo.Video(144, "rSiRjBVMr3E", false, "when you're a london double-decker", "ロンドン2階建バスなあなたに"),
    Inspo.Video(145, "1gxc1ScSrhc", true, "when every day is the olympics", "いつもオリンピックなあなたに"),
    Inspo.Video(146, "KJFDRFFZCuA", false, "when you're not tired at all", "疲れはコナカった？なあなたに"),
    Inspo.Video(147, "Hi6jN0SH7Ew", false, "when something clicks", "ハッとしてGOODなあなたに"),
    Inspo.Video(148, "xU-ZD-GUZWE", false, "when you're the opening ceremony", "オープニングセレモニーなあなたに"),
    Inspo.Video(149, "YvLM_ajVFuc", true, "when you're down", "倒れているあなたに"),
    Inspo.Video(150, "Ila-E5wlSL0", true, "when you want to finish strong", "締めくくりたいあなたに"),
    Inspo.Video(151, "sO9W-04wC4A", true, "when your heart is clean", "心が綺麗なあなたに"),
    Inspo.Video(152, "8r7l4dkcY_g", true, "when you want a beautiful heart", "美しい心を持ちたいあなたに"),
    Inspo.Video(153, "4nIYigAzfjk", false, "when you're a natural", "天然なあなたに"),
    Inspo.Video(154, "e4jBQVv3GHc", true, "when you can't keep to time", "タイムリミットが守れないあなたに"),
    Inspo.Video(155, "Uu2qEZVYzsU", false, "when you're autumn leaves", "もみじなあなたに"),
    Inspo.Video(156, "t3YEQ_UZSvc", true, "when you can't show your feelings", "感情を表に出せないあなたに"),
    Inspo.Video(157, "qypT_QzyroQ", true, "when your heart won't settle", "心が落ち着かないあなたに"),
    Inspo.Video(158, "JjWOIKyNDh0", true, "when you can't picture your life", "自分の人生が描けていないあなたに"),
    Inspo.Video(159, "pVB5k0GZDJc", false, "when you want someone in your corner", "我武者羅應援團に応援されたいあなたに"),
    Inspo.Video(160, "P7vnwLREprE", true, "when you want to open up your luck", "運を開きたいあなたに"),
    Inspo.Video(161, "EI8eIePDbGE", true, "when you want to get better", "上達したいあなたに"),
    Inspo.Video(162, "uQ5sMrYVIYo", true, "when your ego is strong", "自我が強いあなたに"),
    Inspo.Video(163, "omOoyxcxhS0", true, "when you can't find a purpose", "志を持てないあなたに"),
    Inspo.Video(164, "TKFuFYJrqK4", true, "when the past drags you back", "過去に引きずられるあなたに"),
    Inspo.Video(165, "yzimf6CHkIU", true, "when you're boxed in on every side", "八方ふさがりなあなたに"),
    Inspo.Video(166, "hZE7MCi9dLc", false, "when you don't know what hot springs can do", "温泉の力を知らないあなたに"),
    Inspo.Video(167, "W-KXQHi2V0w", true, "when you want to be the world's first", "世界初になりたいあなたに"),
    Inspo.Video(168, "B597ftyvsT8", true, "when you don't want to be a bother", "迷惑をかけたくないあなたに"),
    Inspo.Video(169, "3JJ4noOlh2A", true, "when you want to clear out the bad", "悪いものを取り除きたいあなたに"),
    Inspo.Video(170, "dP8kWZqqijQ", true, "when a first try makes you nervous", "初めての挑戦で不安なあなたに"),
    Inspo.Video(171, "OFhie3YzXOw", true, "when you want to shine", "輝きたいあなたに"),
    Inspo.Video(172, "JmXnXVLn96o", true, "when you think no one trusts you", "誰からも信用されないあなたに"),
    Inspo.Video(173, "jPwNd1HslAs", false, "when you love free space", "自由空間が好きなあなたに Part2"),
    Inspo.Video(174, "_rlD-LMXS2g", true, "when you don't want to be a bother", "迷惑をかけたくないあなたに Part2"),
    Inspo.Video(175, "R8YTqp43-ss", true, "when you want to fall for something", "惚れこみたいあなたに"),
    Inspo.Video(176, "oJPxpCVspfk", true, "when you decide on looks alone", "見た目だけで決めちゃうあなたに"),
    Inspo.Video(177, "GGlnI8SX838", true, "when you can't commit", "覚悟が持てないあなたに"),
    Inspo.Video(178, "8Hv4KzSKMHE", false, "when you love free space", "自由空間が好きなあなたに"),
    Inspo.Video(179, "6YqmDwwKllE", true, "when you need a warning", "警告が必要なあなたに"),
    Inspo.Video(180, "jVI6pHbrLf8", true, "when you've lost your playfulness", "遊び心がないあなたに"),
    Inspo.Video(181, "zuaxdAVh_fI", true, "when you're holding back", "自分を出し切れていないあなたに"),
    Inspo.Video(182, "lze_KIy9Uc0", false, "when you've lost your fighting spirit", "ウルトラ魂がないあなたに"),
    Inspo.Video(183, "NaSzubYpIPg", false, "when you want a bigger house", "もっと広い家に住みたいと思っているあなたに"),
    Inspo.Video(184, "wt7_r_zWJfQ", false, "when you want to marry this summer", "今夏に結婚したいあなたに…"),
    Inspo.Video(185, "eOTyiGuab0g", false, "when you really want to marry this summer", "やっぱりどーしても今夏に結婚したいあなたに…"),
    Inspo.Video(186, "ZQ7kn3w3nz0", true, "when you want to value what makes you you", "個性を大事にしたいあなたに…"),
    Inspo.Video(187, "M_ESB38Z5BA", true, "when your mood is cloudy", "気持ちが曇っているあなたに…"),
    Inspo.Video(188, "AFr6vfPZ9bI", true, "when you can't finish things", "なかなか完成できないあなたに…"),
    Inspo.Video(189, "11Ui45XibA0", false, "good evening", "ウルトラこんばんわのあなたにPart2"),
    Inspo.Video(190, "qoCt0um34Ic", false, "when you're scared of dogs", "犬が恐いあなたに…"),
    Inspo.Video(191, "p07KJ1a_Z5M", false, "good evening", "ウルトラこんばんわのあなたにPart1"),
    Inspo.Video(192, "N-cy2Uig-xE", true, "when things don't go your way", "思うようにいかないあなたに"),
    Inspo.Video(193, "_CQQNSFhu7I", true, "when you've forgotten how to be a kid", "子ども心を忘れてしまったあなたに"),
    Inspo.Video(194, "OrFmdCWg_zY", true, "when you can't stop smirking", "ヘラヘラしちゃうあなたに…"),
    Inspo.Video(195, "3OOyJ36P6uw", true, "when you only want convenience", "便利ばかり求めてしまうあなたに…"),
    Inspo.Video(196, "CQ3QKbDQ7zQ", true, "when you mix up manners and rudeness", "礼儀と無礼をはき違えているあなたに"),
    Inspo.Video(197, "YfsXH0BFbBo", false, "when you're obsessed with abroad", "外国にかぶれているあなたに"),
    Inspo.Video(198, "TbkBgTVxRjM", true, "when you can't own what you do", "自分の行為に責任を持てないあなたに"),
    Inspo.Video(199, "l180zdsMqx4", true, "when you've got it wrong", "勘違いしているあなたに…"),
    Inspo.Video(200, "Rs2s9_F7JTA", true, "when you want big wings", "大きな翼がほしいあなたに…"),
    Inspo.Video(201, "Q-HZf-N8HKo", true, "when you're fighting the devil inside", "心の悪魔と闘っているあなたに…"),
    Inspo.Video(202, "L6n90D5viw8", true, "when you want to be an angel", "天使になりたいあなたに…"),
    Inspo.Video(203, "KIh2hjo-CnE", false, "when you want to see rare medicinal food", "薬膳料理の特別食材を見たいあなたに"),
    Inspo.Video(204, "w22Z7ytY29I", false, "when you want to see an emotional ski jumper", "喜怒哀楽スキージャンパーを見たいあなたに"),
    Inspo.Video(205, "iuFWx5VjhII", true, "when you wonder what you even are", "自分はいったい何なんだろうと思っているあなたに"),
    Inspo.Video(206, "5bh5HPM3JRc", false, "when you don't know why flying fish is so good", "「あご」の美味しさの秘密を知らないあなたに"),
    Inspo.Video(207, "nWseTyUTMGQ", true, "when you want to rise", "コウヨウしたいあなたに"),
    Inspo.Video(208, "KWs1xy2CDtg", true, "when you want to clear out a weak heart", "弱い心を消臭したいあなたに"),
    Inspo.Video(209, "aEQdesUJYY4", true, "when you want to be the real thing", "こだわって本物になりたいあなたに"),
    Inspo.Video(210, "LuafIZdS7PA", true, "when you hate the cold", "寒いのが嫌いなあなたに…"),
    Inspo.Video(211, "8PPuiu-_Hx8", true, "when you want to listen with your heart", "心で聞きたいあなたに…"),
    Inspo.Video(212, "vXzh4Ey-1gQ", true, "when you want to amaze people with something new", "新しい発明で人を驚かせたいあなたに"),
    Inspo.Video(213, "O7knii0-ALc", true, "when you turn negative", "ネガティブになってしまうあなたに"),
    Inspo.Video(214, "PrPM6q_fwN4", true, "when you feel no one understands you", "本当の気持ちを分かってくれないと思っているあなたに"),
    Inspo.Video(215, "tpiTQYl_r-s", true, "when you're about to give up on your dream", "夢をあきらめそうなあなたに"),
    Inspo.Video(216, "bN0pFvrvKkQ", true, "when your palms are sweating", "手に汗握るあなたに"),
    Inspo.Video(217, "VHDdE5a4mnc", true, "when things don't turn out how you hoped", "思ったようにいなかいと思っているあなたに"),
    Inspo.Video(218, "UW_bjoMHpck", true, "when you feel no one sees how hard you try", "頑張りを分かってくれないと思っているあなたに"),
    Inspo.Video(219, "BZ3SeFX4R-c", true, "when you can't let go of common sense", "常識を捨てられないあなたに"),
    Inspo.Video(220, "xokJHwaPQwM", true, "when you can't be yourself", "自分らしくいられないあなたに"),
    Inspo.Video(221, "Rqn5n5H9Z0k", true, "when you think you can't", "できないと思っているあなたに"),
    Inspo.Video(222, "qe7IDacDKGE", true, "when you need an on and an off", "ONとOFFが必要なあなたに…"),
    Inspo.Video(223, "feDbf3vJE4w", true, "when you dwell on small things", "ちっぽけなことを考えてしまうあなたに…"),
    Inspo.Video(224, "eUQCNw20VKk", false, "when you want to ride the narrow road", "細道に乗りたいあなたに…"),
    Inspo.Video(225, "1iJHYXp7u70", true, "when connecting is as far as it goes", "つながったで終わってしまうあなたに"),
    Inspo.Video(226, "3mJubzRZcPQ", false, "when you want to share a japanese heart", "和の心を伝えたいあなたに…"),
    Inspo.Video(227, "pYxyVEqa_Ls", true, "when life won't move forward", "なかなか人生が進まないあなたに"),
    Inspo.Video(228, "6OFk3lhMhRQ", true, "when you doubt everything", "疑い深いあなたに"),
    Inspo.Video(229, "Fu1I6vzrKas", false, "when you want to get your message out", "発新力と発神力で発信力したいあなたに…"),
    Inspo.Video(230, "lbqdjod0Nz0", true, "when you want a bouncing heart", "心を弾ませたいあなたに…"),
    Inspo.Video(231, "A7fhpu_ApDM", true, "when you want to share a feeling", "だよねって想いを共感したいあなたに…"),
    Inspo.Video(232, "rGHOqISzRx8", true, "when you want an exciting challenge", "ワクワクなチャレンジをしたいあなたに"),
    Inspo.Video(233, "UohuVYvo7rE", true, "when you can't choose for yourself", "自分で選ぶことができないあなたに…"),
    Inspo.Video(234, "ZPtCRpL-vCs", true, "when you really want to take on the world", "本気で世界を目指したいあなたに"),
    Inspo.Video(235, "jbJPYp2EH-E", true, "when you want your dream to come true", "夢を叶えたいあなたに"),
    Inspo.Video(236, "Yh-ctq-dS4s", true, "when you don't want to lose to adversity", "逆境に負けたくないあなたに"),
    Inspo.Video(237, "izdViQhwnls", true, "when you want to walk with shuzo", "修造と一緒に歩みたいあなたに"),
    Inspo.Video(238, "NqdAFhzNFrI", true, "when you want a challenge", "チャレンジしたいあなたに"),
    Inspo.Video(239, "7ARNIDCi2eE", true, "when you're not feeling alive", "生き生きしていないあなたに"),
    Inspo.Video(240, "cCAT1t7LbSs", false, "when you want to bloom", "はなっこりーになりたいあなたに"),
    Inspo.Video(241, "AKW_ezjmzrQ", true, "when you can't believe in yourself", "自分が信じられないあなたに"),
    Inspo.Video(242, "oQKUsFsR-hE", true, "when you want to be someone who can", "できる人になりたいあなたに"),
    Inspo.Video(243, "fyZkg9-4dm0", true, "when you want to really cheer someone on", "本気で応援したいあなたに"),
    Inspo.Video(244, "fsdBNLBMCuo", true, "when you've learned to focus", "集中力を学んだあなたに"),
    Inspo.Video(245, "j51QmaDAKvA", true, "when you want to focus", "集中したいあなたに2"),
    Inspo.Video(246, "KJfDzs0Y24M", true, "when you want to focus", "集中したいあなたに1"),
    Inspo.Video(247, "8gNOEybLULI", true, "when you can't focus", "集中できないあなたに"),
    Inspo.Video(248, "RwgUycw4d-o", true, "when you think you've got grit", "根性があると思っているあなたに"),
    Inspo.Video(249, "ystaJusmfD0", true, "when you want to think for yourself", "「自分思考」になりたいあなたに"),
    Inspo.Video(250, "COrx4zuiPq8", true, "when you live freely", "自由に生きているあなたに"),
    Inspo.Video(251, "fK-6xEI76FY", true, "when you've got it wrong", "勘違いしているあなたに"),
    Inspo.Video(252, "9VQ4V3p5BdA", true, "when you've been left out to dry", "干されているあなたに"),
    Inspo.Video(253, "zI31vS3zufI", true, "when your feelings waver", "気持ちがブレているあなたに"),
    Inspo.Video(254, "uVtUjGHQRcY", true, "when you think tradition is old-fashioned", "伝統を古くさいと思っているあなたに"),
    Inspo.Video(255, "O1A4b6xzihs", false, "when you really want to go skiing", "本気でスキーに行きたいあなたに"),
    Inspo.Video(256, "cDPlEylPIh4", true, "when things are too comfortable", "ぬるい環境にいるあなたに"),
    Inspo.Video(257, "INAimxPmcO8", true, "when your heart is cold", "心が寒いあなたに"),
    Inspo.Video(258, "TNRhkU2zTFM", true, "when you give off a bad vibe", "嫌な雰囲気を漂わせているあなたに"),
    Inspo.Video(259, "JG-XYv-j20c", true, "when you want to be reborn", "生まれ変わりたいあなたに"),
    Inspo.Video(260, "EpYSEOnArzE", true, "when you've failed", "失敗してしまったあなたに"),
    Inspo.Video(261, "5IYuNQZgslI", true, "when you think you're alone", "一人だと思っているあなたに"),
    Inspo.Video(262, "IoWjHHrr1Nw", true, "when you don't take care of yourself", "自分に手間をかけていないあなたに"),
    Inspo.Video(263, "ymZLdnboVoI", false, "when you can't hold your drink", "お酒に弱いあなたに"),
    Inspo.Video(264, "uDHUPVhs4F0", false, "when you're one of a kind", "Special Priceなあなたに"),
    Inspo.Video(265, "Bd8V8nb6Ym0", true, "when you can't get back to basics", "初心に戻れないあなたに"),
    Inspo.Video(266, "9DYHGotLAwc", true, "when you can't keep going", "継続できないあなたに"),
    Inspo.Video(267, "YHXA5oDVR2I", true, "when you decide by appearances", "外見で決めてしまうあなたに"),
    Inspo.Video(268, "4fexRP6bj8k", true, "when things aren't going well with people", "人とうまくいってないあなたに"),
    Inspo.Video(269, "Y1ra8-sHws8", false, "when you want to float", "浮きたい！と思っているあなたに…"),
    Inspo.Video(270, "Oi3uBAXpkH4", false, "when you want to unwind after work", "「だれやめ」したいあなたに…"),
    Inspo.Video(271, "XA8ON8mfglk", false, "when you really want to live in quebec", "本気でケベックに住みたいと思っているあなたに…"),
    Inspo.Video(272, "IGPOMDfCSTQ", true, "when you're ready to leap", "Hop Step Jumpなあなたに…"),
    Inspo.Video(273, "tPsmss3ZUO8", true, "when you think you can't jump", "跳べないと思っているあなたに…"),
    Inspo.Video(274, "ph0onzDCd8o", true, "when you wonder if going this far means anything", "ここまでやって意味があるのか？と思っているあなたに…"),
    Inspo.Video(275, "thXhFudRakU", true, "when you can't ask what you forgot", "忘れたことを聞けずにいるあなたに…"),
    Inspo.Video(276, "c8GbGWWFvlk", true, "when your spirits won't lift", "気持ちが上を向かないあなたに"),
    Inspo.Video(277, "N4JV4wihKI4", true, "when your heart won't settle", "心が落ち着かないあなたに"),
    Inspo.Video(278, "IyJHv6O9u1I", true, "when you want to change your heart's colour", "心の色を変えたいあなたに"),
    Inspo.Video(279, "a_B17VRaeUg", true, "when you want to be number one", "1番になりたいあなたに Part1"),
    Inspo.Video(280, "Q-HZT8rDOVM", true, "when you're sinking", "沈んでいるあなたに…"),
    Inspo.Video(281, "p8B_KnWAHTE", true, "when you have a weak side", "「弱さ」があるあなたに"),
    Inspo.Video(282, "R6VJbdEPsH8", true, "when you decide by appearances", "見かけで決めてしまうあなたに…"),
    Inspo.Video(283, "jGKK3oRDiQQ", true, "when you want to run it all the way", "走りきりたいあなたに…"),
    Inspo.Video(284, "l6NBTWTY4cU", true, "when you think you're taking it easy", "楽をしていると思っているあなたに"),
    Inspo.Video(285, "KzQB0HlUGRM", false, "when it's your birthday", "誕生日なあなたに"),
    Inspo.Video(286, "VH9LDJ3AwHY", true, "when you tend to sink", "沈みがちなあなたに"),
    Inspo.Video(287, "VhQKIcT4nZw", true, "when you're trying to get serious", "本気になろうとしているあなたに"),
    Inspo.Video(288, "MT_-YWe9Wxk", false, "when you get angry", "イカってしまうあなたに"),
    Inspo.Video(289, "M2pKNgh-ZDI", false, "when you want a handshake", "修ちゃんと握手したいあなたに"),
    Inspo.Video(290, "Z2bGJiTo2N4", true, "when you judge people by their looks", "人を見かけで判断してしまうあなたに"),
    Inspo.Video(291, "Ry9iqHZDpRc", true, "when you have no colour of your own", "自分の色がないあなたに"),
    Inspo.Video(292, "pR9Xqw2uVHE", true, "when you always walk along the edges", "はじっこばかり歩いているあなたに"),
    Inspo.Video(293, "l3uroy79jqM", false, "when you want to be serious in the toilet", "トイレで本気を伝えたいあなたに"),
    Inspo.Video(294, "q8UMwH6umlA", false, "when you want to be moved by a toilet", "トイレに感動したいあなたに"),
    Inspo.Video(295, "mqBB3d-8fD8", true, "when you can't live in the now", "今を生きれないあなたに…"),
    Inspo.Video(296, "Kp_Q_Q-Qplg", true, "when you're living on the surface", "上っ面だけで生きているあなたに"),
    Inspo.Video(297, "vzw6DgU7JK8", true, "when you're not no good", "ダメじゃないあなたに"),
    Inspo.Video(298, "rWRkTpevQ2Q", true, "when looks make you give up", "見た目で諦めてしまうあなたに"),
    Inspo.Video(299, "ydW4Qm-Q2Sc", true, "when you push yourself forward too much", "出しゃばってしまうあなたに"),
    Inspo.Video(300, "aaGRFxbDJC0", true, "when you have no focus", "集中力のないあなたに"),
    Inspo.Video(301, "3SNLPEcdh5M", true, "when you're stuck in fixed ideas", "固定観念を持っているあなたに"),
    Inspo.Video(302, "JKviKHfoNyA", true, "when you think you've lost everything", "すべてを失ったと思っているあなたに"),
    Inspo.Video(303, "Bqm5ZYYLlIc", true, "when you think you're disliked", "嫌われていると思っているあなたに"),
    Inspo.Video(304, "5eSKUDzQreU", true, "when you can't live fair and square", "正々堂々と生きられないあなたに"),
    Inspo.Video(305, "7WhJvR24Ma8", true, "when your surroundings overwhelm you", "周りの環境に圧倒されてしまうあなたに"),
    Inspo.Video(306, "tAzQQDwQCZE", true, "when you can't believe nothing is impossible", "不可能なんてないと思えないあなたに"),
    Inspo.Video(307, "l73mdL_nDFc", true, "when you judge by appearances", "見た目で判断してしまうあなたに"),
    Inspo.Video(308, "C-lA8JjKGpc", true, "when you can't get serious", "本気になれないあなたに"),
    Inspo.Video(309, "mmUnquz-rdM", false, "when you want festival music to make your heart dance", "祭りばやしでこころを踊らせたいあなたに"),
    Inspo.Video(310, "eM6A8SjJQG0", true, "when you think you'll never get ahead", "出世できないと思っているあなたに"),
    Inspo.Video(311, "mbu3AIKk2qQ", true, "when another day is done", "今日もおわったと思ったあなたに"),
    Inspo.Video(312, "99_GG3uvHLI", true, "when you lack imagination", "想像力の足りないあなたに"),
    Inspo.Video(313, "4lZrGulru_A", true, "when exams are finally here", "いよいよ受験！のあなたに"),
    Inspo.Video(314, "HP_WeboHsVI", true, "when you want to change the world", "世界を変えたいあなたに①"),
    Inspo.Video(315, "8FNWAb3LL9E", true, "when you want to change the world", "世界を変えたいあなたに②"),
    Inspo.Video(316, "SjwJqJrq6dA", true, "when you think no one will protect you", "誰も守ってくれないと思っているあなたに"),
    Inspo.Video(317, "-nbqA2N3EBs", true, "when you can't like yourself", "自分を好きになれないあなたに"),
    Inspo.Video(318, "eD7bVmKyJ94", true, "when you want to win", "勝負に勝ちたいあなたに"),
    Inspo.Video(319, "HovI4JykeFo", true, "when you hate failing", "失敗がイヤなあなたに"),
    Inspo.Video(320, "dVPWjCJzi6E", true, "when you've lost your way", "自分の行く道がわからなくなったあなたに…"),
    Inspo.Video(321, "crEu66AwS9A", true, "when you're giving up on your dream", "夢をあきらめようとしているあなたに"),
    Inspo.Video(322, "Vmol4aVfaQg", true, "when you keep clashing", "ぶつかり合ってしまうあなたに"),
    Inspo.Video(323, "vrLkoy6kdFs", true, "when you can't chase your goal your own way", "自分らしく目標を目指せないあなたに"),
    Inspo.Video(324, "LbfnxHBRMo8", true, "when hearts can't come together", "心が一つになれないあなたに"),
    Inspo.Video(325, "1D92_zb6uMg", true, "when you can't get your feelings across", "想いを伝えられないあなたに"),
    Inspo.Video(326, "6OVR-lWeGPE", true, "when people are counting on you", "期待をかけられているあなたに"),
    Inspo.Video(327, "CoP2y4C9YQk", true, "when you can't be yourself", "自分らしくいられないあなたに"),
    Inspo.Video(328, "ormRvwhJwz8", true, "when your heart feels small", "心がちっぽけなあなたに"),
    Inspo.Video(329, "I8U7Hyw3WYo", false, "when you want to eat to win", "EAT TO WINしたいあなたに"),
    Inspo.Video(330, "lcIjE-CqwsY", true, "when you can't surprise anyone", "サプライズできないあなたに"),
    Inspo.Video(331, "tLV1G3-mSwk", true, "when you think it's always the same", "いつも同じだと思っているあなたに"),
    Inspo.Video(332, "Rz_kYBPYgsI", true, "when you want to feel something", "何かを感じたいあなたに"),
    Inspo.Video(333, "S5kXu_hZMAU", true, "when you give up halfway", "途中であきらめてしまうあなたに"),
    Inspo.Video(334, "rHOKTOKVg-U", true, "when you can't fire people up", "人を熱くできないあなたに"),
    Inspo.Video(335, "JGlX7JjnV7Q", true, "when you want to be reborn as a new you", "新しい自分に生まれ変わりたいあなたに。"),
    Inspo.Video(336, "a5yGF8dRe1Y", false, "when you want to stand tall", "姿勢天使シャーン造になりたいあなたに"),
    Inspo.Video(337, "DDWV1n6xOIo", true, "when you want to be like an angel", "天使のようになりたいあなたに"),
    Inspo.Video(338, "JPTbd5whMSw", true, "when you want a clear heart", "きれいな心を持ちたいあなたに"),
    Inspo.Video(339, "Wo9WbkIWvis", true, "when you can't control yourself", "自分をコントロールできないあなたに"),
    Inspo.Video(340, "AmVpWEa4W30", true, "when you're anxious on the edge", "崖っぷちで不安を感じているあなたに"),
    Inspo.Video(341, "us8pTZrC3EA", true, "when you're on the edge", "崖っぷちにいるあなたに"),
    Inspo.Video(342, "w3_Wjvxdqp0", true, "when you worry what people think", "人の評価を気にしてしまうあなたに"),
    Inspo.Video(343, "-_3Bi-1fHTw", true, "when you can't wipe out a weak heart", "弱い心を滅れないあなたに"),
    Inspo.Video(344, "KjOr5barw04", true, "when you give up", "諦めてしまうあなたに"),
    Inspo.Video(345, "nHfsuBdOczE", true, "when you're too busy to know what to do", "忙しくて何をすればいいか分からないあなたに"),
    Inspo.Video(346, "BjCn0WaHUuw", true, "when you're just drifting through the days", "なんとなく毎日過ごしちゃってるあなたに"),
    Inspo.Video(347, "ucJ6C9E5s24", true, "when you're taking things too seriously", "気持ちが深刻になりすぎているあなたに"),
    Inspo.Video(348, "S6lBaxSohW8", true, "when you can't enjoy imagining", "想像を楽しめないあなたに"),
    Inspo.Video(349, "G7rIUihXajU", true, "when you think nothing ever goes right", "うまくいかないことばかりと思っているあなたに"),
    Inspo.Video(350, "OwwWyazU2xk", true, "when you can't get serious", "本気になれないあなたに"),
    Inspo.Video(351, "eZgTG01dhTc", true, "when you think you don't matter", "自分は意味がないと思っているあなたに"),
    Inspo.Video(352, "hySSRHwTiIM", true, "when you can't picture it", "イメージできないあなたに"),
    Inspo.Video(353, "qkC6_BH0Ny4", true, "when you want to be happy", "し泡せになりたいあなたに"),
    Inspo.Video(354, "RepaSkdVXZc", true, "when you want to be like a flower", "花のようになりたいあなたに"),
    Inspo.Video(355, "NdcAYT-FUHM", true, "when you're caught in a negative spiral", "ネガティブな渦の中にいるあなたに"),
)
